### ISSUE TITLE
[docs] Document software and hardware requirements

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#102]
Questions like the following are recurrent:

- are there any packages I should pre-install prior to running the Ansible playbook?
- Are there any configuration steps I should perform on the server prior to running the playbook to ensure a clean install?
- what are the Hardware recommendations?

**Comment by atb00ker** [comment]
@nemesisdesign 
I recently tried to install openwisp2 in an empty container and realized that `systemd` is a requirement for postfix to restart in the debian systems, should that be documented?
Thanks

**Comment by nemesisdesign** [comment]
@atb00ker isn't that detail handled by ansible? Or do we have some systemd specific directive in our role?

**Comment by nemesisdesign** [comment]
@atb00ker you're right, it was probably a workaround I added a while ago, can you create an issue for that please?

**Comment by atb00ker** [comment]
Done that! :smile:

**Comment by nickberry17** [comment]
https://github.com/openwisp/ansible-openwisp2/pull/167/commits/aca6f0832f2ec8af5a912d27a9da7cb18c1912a0
