### ISSUE TITLE
[bug] Travis not working for pull requests

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#103]
Unfortunately currently, travis is only checking the `openwisp/ansible-openwisp2/master`.
This is a problem because pull requests are not checked before being merged.

A dynamic way to check the current source & branch is required. Currently, [source & branch are hard-coded](https://github.com/openwisp/ansible-openwisp2/blob/ebec17fec8bfdb2cdd0abdbc81bc0163dc349fde/tests/requirements.yml#L3-L5).

**Comment by atb00ker** [comment]
Currently, changing [this line](https://github.com/openwisp/ansible-openwisp2/blob/ebec17fec8bfdb2cdd0abdbc81bc0163dc349fde/tests/test.yml#L21)  to `role_under_test` is working for me.

**Comment by nemesisdesign** [comment]
@hispanico is there any way with which we can tell travis/gitlab to use the current cloned repository code?

With the current state of things we can't check whether a pull request contains bugs or not because the build will always test the official master branch of ansible-openwisp2.
