### ISSUE TITLE
[bug] fails on rhel7

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#104]
**Distribution information:**
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"

**Error:**
```
failed: [vagrant.box] (item=mailx) => {"changed": false, "item": "mailx", "msg": "No package matching 'mailx' found available, installed or updated", "rc": 126, "results": ["No package matching 'mailx' found available, installed or updated"]}
```

**Comment by nemesisdesign** [comment]
Does it still fail? If yes @atb00ker can you create a GCI task for this please? And If not close please?
PS: if you manage to create the GCI task, add me and @hispanico as mentors as well please.

**Comment by atb00ker** [comment]
@nemesisdesign 
I also tested it with rhel6, it's failing for the same reason!

I ran this on my system. It looks like an error with `TASK [Stouts.postfix : Install requirements (RedHat)` and not `ansible-openwisp2`.

**Comment by nemesisdesign** [comment]
If that's the case, this issue is related to https://github.com/openwisp/ansible-openwisp2/issues/57, I'd like to remove the dependency on my fork but I'm not sure if we can do this now.
