### ISSUE TITLE
[tests] Improve output of runtests.sh

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#108]
**Reserved for GCI**

The output generated by the script in `tests/runtests.sh` can be improved:

- the `-x` option of bash in the beginning of the script is not necessary, we can remove it
- we should add a description of what is about to happen before each test, eg: `echo "Testing web server..."` and `echo "Launching openwisp tests with django"`

**Comment by hispanico** [comment]
We should add a color definition and replace echo with printf like the following:

```
# Pretty colors.
red='\033[0;31m'
green='\033[0;32m'
neutral='\033[0m'

printf ${green}"Running playbook again: idempotence test"${neutral}
[..]
    && (printf ${green}'Idempotence test: pass'${neutral}"\n") \
    || (printf ${red}'Idempotence test: fail'${neutral}"\n" && exit 1)
```
