### ISSUE TITLE
nginx spdy

### ISSUE THREAD

**Issue by netminion** [openwisp/ansible-openwisp2#12]
i think the nginx spdy module is replaced by httpd2. But HTTP/2 needs OpenSSL 1.0.2+ and most distributions deliver older OpenSSL Versions.

https://www.nginx.com/blog/supporting-http2-google-chrome-users/

**Comment by nemesisdesign** [comment]
Hi @netminion and welcome,

on Debian 8:

```
# openssl version
OpenSSL 1.0.1t  3 May 2016
```

I think Debian 9 has a more recent version, @ritwickdsouza recently added support for Debian 9 via #10, so maybe we could test this feature there.

Ideally we should support both options so users using older OS can use SPDY if they like, while users using newer OS can use HTTP2.

Adding support should be pretty easy, it's just a matter of adding a new [default variable which defaults to false](https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml) and add an extra if in the [nginx jinja2 template](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/nginx.j2).

**Comment by netminion** [comment]
Hi @nemesisdesign 
i created the pullrequest #13 

My personal opinion is to set the openwisp2_nginx_spdy variable to false because you get an error on a default CentOS7 setup (maybe others distributions too). I set http2 to false because most OpenSSL Version are a little bit outdated and don't support ALPN.

**Comment by nemesisdesign** [comment]
@netminion Yes you are right. I've introduced the change in 6745aaa
