### ISSUE TITLE
deprecation warning in Install extra python

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#126]
- TASK [openwisp.openwisp2 : Install extra python packages] ******************************************************************************
[DEPRECATION WARNING]: Invoking "pip" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply 
multiple items and specifying `name: "{{ item }}"`, please use `name: '{{ openwisp2_extra_python_packages }}'` and remove the loop. 
This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

**Comment by okraits** [comment]
It also appears with `apt` in `Stouts.postfix`.
