### ISSUE TITLE
[bug] run handler to reload systemd only when system is installed

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#131]
`reload systemd` handler will fail the role when system is not running on systemd. 
Running that handler only when `systemd` is installed should solve the problem.

**Comment by nemesisdesign** [comment]
Maybe this is not needed anymore or there's a better way to do it: https://github.com/openwisp/ansible-openwisp2/blob/master/handlers/main.yml#L5-L7
