### ISSUE TITLE
[nginx] Add a default SSL webserver which returns 404

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#135]
We should add an additional nginx webserver which acts as a default for SSL and catches all requests that would trigger "HOST not allowed" error in django.

Something like this should do:

```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    ssl on;
    ssl_certificate <SSL_CERT_HERE>;
    ssl_certificate_key <SSL_CERT_KEY_HERE>;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
    }
}

```

**Comment by dwang** [comment]
I'm interested in implementing this.

If I understand correctly, any SSL connection to the server that is not to a host defined in `openwisp2_allowed_hosts` should have the connection closed. But, I don't understand why there should not be a matching configuration that is listening on port 80.

**Comment by nemesisdesign** [comment]
@dwang we need port 80 too, I updated the example

**Comment by dwang** [comment]
@nemesisdesign If I'm not mistaken, the new example will try to serve files in `/var/www/html` (but there should not be any except the default Nginx page?) before returning a 404. Should the Nginx server return 404 or 444?

**Comment by nemesisdesign** [comment]
I changed my mind after doing some testing, I would use `404`, I updated the title, thanks for pointing it out
