### ISSUE TITLE
Redis server installation failed error

### ISSUE THREAD

**Issue by haccks** [openwisp/ansible-openwisp2#136]
I am struggling to deploy openwisp2 on production server. I followed instructions over [here](https://github.com/openwisp/ansible-openwisp2#usage-tutorial) but every time  I am getting this error:

fatal: [test.adl-icm.com]: FAILED! => {"cache_update_time": 1553151222, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'redis-server'' failed: E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "rc": 100, "stderr": "E: Sub-process /usr/bin/dpkg returned an error code (1)\n", "stderr_lines": ["E: Sub-process /usr/bin/dpkg returned an error code (1)"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nredis-server is already the newest version (5:4.0.9-1ubuntu0.1).\n0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.\n2 not fully installed or removed.\nAfter this operation, 0 B of additional disk space will be used.\nSetting up redis-server (5:4.0.9-1ubuntu0.1) ...\r\nJob for redis-server.service failed because a timeout was exceeded.\r\nSee \"systemctl status redis-server.service\" and \"journalctl -xe\" for details.\r\ninvoke-rc.d: initscript redis-server, action \"start\" failed.\r\n* redis-server.service - Advanced key-value store\r\n   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)\r\n   Active: activating (auto-restart) (Result: timeout) since Thu 2019-03-21 12:24:31 IST; 29ms ago\r\n     Docs: http://redis.io/documentation,\r\n           man:redis-server(1)\r\ndpkg: error processing package redis-server (--configure):\r\n installed redis-server package post-installation script subprocess returned error exit status 1\r\ndpkg: dependency problems prevent configuration of redis:\r\n redis depends on redis-server (<< 5:4.0.9-1ubuntu0.1.1~); however:\r\n  Package redis-server is not configured yet.\r\n redis depends on redis-server (>= 5:4.0.9-1ubuntu0.1); however:\r\n  Package redis-server is not configured yet.\r\n\r\ndpkg: error processing package redis (--configure):\r\n dependency problems - leaving unconfigured\r\nErrors were encountered while processing:\r\n redis-server\r\n redis\r\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "redis-server is already the newest version (5:4.0.9-1ubuntu0.1).", "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.", "2 not fully installed or removed.", "After this operation, 0 B of additional disk space will be used.", "Setting up redis-server (5:4.0.9-1ubuntu0.1) ...", "Job for redis-server.service failed because a timeout was exceeded.", "See \"systemctl status redis-server.service\" and \"journalctl -xe\" for details.", "invoke-rc.d: initscript redis-server, action \"start\" failed.", "* redis-server.service - Advanced key-value store", "   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)", "   Active: activating (auto-restart) (Result: timeout) since Thu 2019-03-21 12:24:31 IST; 29ms ago", "     Docs: http://redis.io/documentation,", "           man:redis-server(1)", "dpkg: error processing package redis-server (--configure):", " installed redis-server package post-installation script subprocess returned error exit status 1", "dpkg: dependency problems prevent configuration of redis:", " redis depends on redis-server (<< 5:4.0.9-1ubuntu0.1.1~); however:", "  Package redis-server is not configured yet.", " redis depends on redis-server (>= 5:4.0.9-1ubuntu0.1); however:", "  Package redis-server is not configured yet.", "", "dpkg: error processing package redis (--configure):", " dependency problems - leaving unconfigured", "Errors were encountered while processing:", " redis-server", " redis"]}
	to retry, use: --limit @/Users/dankhan/openwisp2-ansible-playbook/playbook.retry

How to fix it?

**Comment by atb00ker** [comment]
Hi, 

Please share information about your server including:
1. Which distribution are you running.
2. Do you have any other application installed or are you trying to install openwisp on a fresh image?

Thanks.

**Comment by haccks** [comment]
Hi @atb00ker,
1. I am using Ubuntu 18.04
2. It's a fresh image. 
3. Here is the output:

```
Mar 21 14:10:06 e2e-36-70.e2enetworks.net.in systemd[1]: redis-server.service: Scheduled restart job, restart counter is at 723.
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit redis-server.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
Mar 21 14:10:06 e2e-36-70.e2enetworks.net.in systemd[1]: Stopped Advanced key-value store.
-- Subject: Unit redis-server.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit redis-server.service has finished shutting down.
Mar 21 14:10:06 e2e-36-70.e2enetworks.net.in systemd[1]: Starting Advanced key-value store...
-- Subject: Unit redis-server.service has begun start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit redis-server.service has begun starting up.
Mar 21 14:10:36 e2e-36-70.e2enetworks.net.in sshd[20166]: PAM unable to dlopen(pam_ck_connector.so): /lib/security/pam_ck_connector.so: cannot open shared object file: No such fi
Mar 21 14:10:36 e2e-36-70.e2enetworks.net.in sshd[20166]: PAM adding faulty module: pam_ck_connector.so
Mar 21 14:10:36 e2e-36-70.e2enetworks.net.in sshd[20166]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.111.139.211  user=root
Mar 21 14:10:38 e2e-36-70.e2enetworks.net.in sshd[20166]: Failed password for root from 223.111.139.211 port 38714 ssh2
Mar 21 14:10:40 e2e-36-70.e2enetworks.net.in sshd[20166]: Failed password for root from 223.111.139.211 port 38714 ssh2
Mar 21 14:10:42 e2e-36-70.e2enetworks.net.in sshd[20166]: Failed password for root from 223.111.139.211 port 38714 ssh2
Mar 21 14:10:42 e2e-36-70.e2enetworks.net.in sshd[20166]: Received disconnect from 223.111.139.211 port 38714:11:  [preauth]
Mar 21 14:10:42 e2e-36-70.e2enetworks.net.in sshd[20166]: Disconnected from authenticating user root 223.111.139.211 port 38714 [preauth]
Mar 21 14:10:42 e2e-36-70.e2enetworks.net.in sshd[20166]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.111.139.211  user=root
Mar 21 14:10:44 e2e-36-70.e2enetworks.net.in sshd[20168]: PAM unable to dlopen(pam_ck_connector.so): /lib/security/pam_ck_connector.so: cannot open shared object file: No such fi
Mar 21 14:10:44 e2e-36-70.e2enetworks.net.in sshd[20168]: PAM adding faulty module: pam_ck_connector.so
Mar 21 14:10:44 e2e-36-70.e2enetworks.net.in sshd[20168]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.111.139.211  user=root
Mar 21 14:10:47 e2e-36-70.e2enetworks.net.in sshd[20168]: Failed password for root from 223.111.139.211 port 45278 ssh2
Mar 21 14:10:47 e2e-36-70.e2enetworks.net.in sshd[20168]: Bad packet length 812675084. [preauth]
Mar 21 14:10:47 e2e-36-70.e2enetworks.net.in sshd[20168]: ssh_dispatch_run_fatal: Connection from authenticating user root 223.111.139.211 port 45278: message authentication code
Mar 21 14:10:49 e2e-36-70.e2enetworks.net.in sshd[20170]: PAM unable to dlopen(pam_ck_connector.so): /lib/security/pam_ck_connector.so: cannot open shared object file: No such fi
Mar 21 14:10:49 e2e-36-70.e2enetworks.net.in sshd[20170]: PAM adding faulty module: pam_ck_connector.so
Mar 21 14:10:49 e2e-36-70.e2enetworks.net.in sshd[20170]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=223.111.139.211  user=root
Mar 21 14:10:51 e2e-36-70.e2enetworks.net.in sshd[20170]: Failed password for root from 223.111.139.211 port 50374 ssh2
lines 1825-1862/1862 (END)
```

**Comment by atb00ker** [comment]
Okay,
Our CI for fresh image of Ubuntu 18.04 reports it's working fine. [Check [here](https://travis-ci.org/openwisp/ansible-openwisp2/jobs/508897903)]

Can you please try manually installing `redis-server` and then running the ansible script?
Please let me know if you face an error while manual installation or if works out! :smile:

**Comment by haccks** [comment]
I installed redis server manually and now I am getting this error:

`fatal: [test.adl-icm.com]: FAILED! => {"changed": false, "msg": "Unable to start service redis-server: Job for redis-server.service failed because a timeout was exceeded.\nSee \"systemctl status redis-server.service\" and \"journalctl -xe\" for details.\n"}`

**Comment by atb00ker** [comment]
Maybe restarting manually and checking what's going on in the server and causing the failure will help. `journalctl -xe` might also give clues.

A quick shortcut *may* be to comment out the handler that restarts the redis-server (Easy job if you have worked with Ansible) !

**Comment by nemesisdesign** [comment]
The current builds in the latest dev versions do not show this issue, hence I think it's solved and I'm closing. If anyone is still seeing this issue with the latest master of this role let us know.
