### ISSUE TITLE
Upgrade fails on CentOS7

### ISSUE THREAD

**Issue by moonwolf-github** [openwisp/ansible-openwisp2#141]
Came back after a long time and upgrade fails with:
`fatal: [openwisp2]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput", "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/django/core/management/__init__.py\", line 371, in execute_from_command_line\n    utility.execute()\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/django/core/management/__init__.py\", line 347, in execute\n    django.setup()\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/django/__init__.py\", line 24, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/django/apps/registry.py\", line 112, in populate\n    app_config.import_models()\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/django/apps/config.py\", line 198, in import_models\n    self.models_module = import_module(models_module_name)\n  File \"/usr/lib64/python3.4/importlib/__init__.py\", line 109, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 2254, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 2237, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 2226, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 1200, in _load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 1129, in _exec\n  File \"<frozen importlib._bootstrap>\", line 1471, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 321, in _call_with_frames_removed\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/openwisp_users/models.py\", line 11, in <module>\n    from organizations.abstract import (AbstractOrganization,\n  File \"/opt/openwisp2/env/lib/python3.4/site-packages/organizations/abstract.py\", line 29, in <module>\n    from django.core.urlresolvers import reverse\nImportError: No module named 'django.core.urlresolvers'\n", "path": "/opt/openwisp2/env/bin:/sbin:/bin:/usr/sbin:/usr/bin", "syspath": ["/tmp/ansible_django_manage_payload_5q1O3N/ansible_django_manage_payload.zip", "/usr/lib64/python27.zip", "/usr/lib64/python2.7", "/usr/lib64/python2.7/plat-linux2", "/usr/lib64/python2.7/lib-tk", "/usr/lib64/python2.7/lib-old", "/usr/lib64/python2.7/lib-dynload", "/usr/lib64/python2.7/site-packages", "/usr/lib64/python2.7/site-packages/gtk-2.0", "/usr/lib/python2.7/site-packages"]}`

Looks like it mixing versions of Django/python?

Also i had to put
```
[openwisp2:vars]
ansible_python_interpreter=/usr/bin/python
```
in `hosts` file.

**Comment by atb00ker** [comment]
Hi,

Currently we have temprarorily dropped Fedora / CentOS / RHEL. It has maintenance issues right now. 
Eventually, hopefully we will get back to it however, right now, you may use Ubuntu 18.04 or Debian 9 or 10 should work fine on these!

If you think there is something to be added in this comment chain, please feel free to open this issue again. :smile:
