### ISSUE TITLE
Errore task "openwisp.openwisp2 : migrate

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2#143]
Debian 9 netinstall con solo abilitato ipv6 (openwisp2.nnxx.ninux.org).
Il playbook lanciato è quello presente nel git di ninux senza monitoring (è su un repo privato).
Il playbook non installa service_identity ed ho dovuto installarlo manualmente.
pip install service_identity

il playbook: https://pastebin.com/NRChdDnb

L'errore: https://pastebin.com/mV6DTfw8

**Comment by atb00ker** [comment]
Google translate: 
```
Debian 9 netinstall with only ipv6 enabled (openwisp2.nnxx.ninux.org).
The playbook launched is the one present in the ninux git without monitoring (it is on a private repo).
The playbook does not install service_identity and I had to install it manually.
pip install service_identity
```

Thanks for the information: `service_identity` has been added [here](https://github.com/openwisp/ansible-openwisp2/blob/master/tasks/pip.yml#L58).

Hopefully when the release is fixed this will be fixed as well, I'll test and close it! :smile:

**Comment by nemesisdesign** [comment]
Should be fixed!
