### ISSUE TITLE
Issue installing openwisp2

### ISSUE THREAD

**Issue by jarkle** [openwisp/ansible-openwisp2#145]
Running command:
 ansible-playbook -i hosts playbook.yml -u root -k --become -K

Getting this error:
TASK [openwisp.openwisp2 : set redis to listen on ipv4 (RedHat & CentOS)] *************************************************************************************************************************************************************************************************************
fatal: [openwisp2]: FAILED! => {"changed": false, "module_stderr": "Shared connection to openwisp2 closed.\r\n", "module_stdout": "/root/.ansible/tmp/ansible-tmp-1572907422.9474678-122253876206538/AnsiballZ_lineinfile.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\r\n  import imp\r\nTraceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1572907422.9474678-122253876206538/AnsiballZ_lineinfile.py\", line 114, in <module>\r\n    _ansiballz_main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1572907422.9474678-122253876206538/AnsiballZ_lineinfile.py\", line 106, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1572907422.9474678-122253876206538/AnsiballZ_lineinfile.py\", line 49, in invoke_module\r\n    imp.load_module('__main__', mod, module, MOD_DESC)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 234, in load_module\r\n    return load_source(name, filename, file)\r\n  File \"/usr/lib64/python3.7/imp.py\", line 169, in load_source\r\n    module = _exec(spec, sys.modules[name])\r\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\r\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\r\n  File \"/tmp/ansible_lineinfile_payload_xoevlzeh/__main__.py\", line 567, in <module>\r\n  File \"/tmp/ansible_lineinfile_payload_xoevlzeh/__main__.py\", line 558, in main\r\n  File \"/tmp/ansible_lineinfile_payload_xoevlzeh/__main__.py\", line 338, in present\r\nAttributeError: 'bool' object has no attribute 'expand'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************************
openwisp2                  : ok=15   changed=0    unreachable=0    failed=1    skipped=31   rescued=0    ignored=0

**Comment by atb00ker** [comment]
Support for centos is temprarorily dropped on our end.
However, it looks like ansible issue, I read "Module Failure", please share the version of ansible and OS you are installing on.

**Comment by jarkle** [comment]
Fedora Server 30
On client pc, ansible 2.8.6

**Comment by jarkle** [comment]
> Support for centos is temprarorily dropped on our end.
> However, it looks like ansible issue, I read "Module Failure", please share the version of ansible and OS you are installing on.

Should I try using a different OS for the client machine?

**Comment by atb00ker** [comment]
Yes, that'll be ideal. I think Ubuntu 18.04 or Debian 9 or 10 should work fine. (Tested on these recently)
 Fedora / CentOS / RHEL family currently has issues unfortunately so we have removed their support from docs as well!
