### ISSUE TITLE
Documentation for adding Host-only Network Adapter

### ISSUE THREAD

**Issue by TheOneAboveAllTitan** [openwisp/ansible-openwisp2#148]
In the README, the path for adding Host-only Network Adapter is `File > Preferences > Network > Host-only Networks` while I installed `Oracle VM VirtualBox VM Selector v6.0.14_Ubuntu` on Pop OS and the path is `File > Host Network Manager`. 

The same is also mentioned in changelogs of `VirtualBox 5.2.0 (released October 17, 2017)` available at [https://www.virtualbox.org/wiki/Changelog-5.2](https://www.virtualbox.org/wiki/Changelog-5.2).

> GUI: Host-only Network Manager implemented to simplify managing corresponding networks and their attributes

**Comment by atb00ker** [comment]
They keep changing it! 
Can I please use this for GCI? :smile:

**Comment by TheOneAboveAllTitan** [comment]
Yeah, sure! @atb00ker
