### ISSUE TITLE
[travis] Idempotence test fails randomly at times

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#159]
You can see, that `runtests.sh` [here](https://travis-ci.org/openwisp/ansible-openwisp2/jobs/633900953#L1581) is failing on `Idempotence test`, although on other distors in the same build it works ok (and those failing distros aren't the same every build). You can see this behavior in the master branch as well:
- [c38b8fd](https://travis-ci.org/openwisp/ansible-openwisp2/builds/626669311?utm_source=github_status&utm_medium=notification)
- [abcff2c](https://travis-ci.org/openwisp/ansible-openwisp2/builds/626729788?utm_source=github_status&utm_medium=notification)

Re-running the tests may pass the idempotence tests.
Need to find out the reason behind this, if it's a travis related problem, let's add this to known-issues in the pull requests! :smile:

The step that re-runs and causes error :
```
TASK [role_under_test : Install openwisp2 controller and its dependencies] *****
changed: [localhost]
```

**Comment by nemesisdesign** [comment]
@atb00ker can we have the idempotence test fail with more detailed information?

**Comment by atb00ker** [comment]
Currently, I just found out that "Install openwisp2 controller and its dependencies" is failing.
I'll have to research to see if an option like `verbose` is available! :smile:

**Comment by dwang** [comment]
I've seen this recently too. Have there been any changes to cause the failure or is it just Travis being weird?

**Comment by atb00ker** [comment]
@dwang I am not certain, but I think it may be related to the fact that we have not released `openwisp-controller` in a while, now that it's released, let's see if it happens again, please ping here if you notice it again! :smile:

**Comment by nemesisdesign** [comment]
It happens a lot. I changed the build so it doesn't fail because of that because that's been slowing us down a lot.
I'd keep this open to see if anyone can find the reason for which the playbook is not idempotent some of the time.

**Comment by hispanico** [comment]
ERROR: Idempotence test failed because of the following tasks:
* [instance] => openwisp.openwisp2 : create "/opt/openwisp2/log"

It seems this task cause the idempotence test failure:
```yaml
- name: create "{{ openwisp2_path }}/log"
  file:
    path: "{{ openwisp2_path }}/log"
    state: directory
    group: "{{ www_group }}"
    mode: 0775
    recurse: yes
```

**Comment by atb00ker** [comment]
I think we haven't seen anything funny recently, so closing for now, if someone has seen something, please reopen.

**Comment by nemesisdesign** [comment]
:+1: thanks
