### ISSUE TITLE
export and import config server

### ISSUE THREAD

**Issue by mikysal78** [openwisp/ansible-openwisp2#163]
For migrate server config on other hw?
It's possible export config server, device etc... and import?
Thanks.

**Comment by atb00ker** [comment]
Hi,

This looks like a support ticket not a bug.
This is our bug tracker.
Please use https://groups.google.com/forum/#!forum/openwisp for support.


Best,
Ajay Tripathi

**Comment by atb00ker** [comment]
> It's possible export config server, device etc... and import?
Your data is inside database (postgres) & your media (floor plan images etc) is in `/opt/openwisp2/media` that's all you need to backup! :smile:
