### ISSUE TITLE
[feature] Add optional network-topology module

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#17]
When the first release of [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topolgy) is ready, add a way to install, configure and upgrade the module.

@rohithasrk will help me implementing this feature. @leonardomaccari and @mikysal78 are also interested in using this feature.

It would be great to figure out a general way to extend ansible-openwisp2 with additional roles, that way we could allow adding extra features to ansible-openwisp2 without complicating it too much: additional features like the network-topology and the freeradius modules would then become additional ansible roles that depend on ansible-openwisp2, but this is just an early-stage idea.

**Comment by rohithasrk** [comment]
@nemesisdesign Would like to work. How do I proceed?

**Comment by nemesisdesign** [comment]
Setup a test environment, you need a VM or an lxc which you can destroy and recreate to test the playbook. I suggest you to create a fresh VM/lxc, set up the basics (like update system packages and setup internet connection) and then create a template/snapshot from it that you can use to re-create the test instance when you destroy it.

Clone this repo and create a symbolic link from `/etc/ansible/roles/` to it, call the symbolic link `openwisp.openwisp2` so that `/etc/ansible/roles/openwisp.openwisp2` points to your repo.

Then run the playbook normally at least once on your test VM/lxc.

Then start play with the code of the playbook to understand how it works, I suggest you to start documenting yourself about ansible, there are plenty of online resources and I have a short ebook I can pass to you if you like.

When you are comfortable going ahead, we should add a variable that allows users to enable the network topology module (eg: `openwisp2_network_topology`), plus a few more variables to configure it (at least two variables that allow to install the development versions of [django-netjsongraph](https://github.com/netjson/django-netjsongraph) and [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology)).

When `openwisp2_network_topology` is enabled, the module should be installed and configured in the [settings](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/openwisp2/settings.py) and [urls](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/openwisp2/urls.py).

**Comment by nemesisdesign** [comment]
Implemented by #19, closing this. Thanks to @rohithasrk! 👍
