### ISSUE TITLE
Fatal error on 'Install cryptography from pip' - cffi version exception

### ISSUE THREAD

**Issue by jon-wrennall** [openwisp/ansible-openwisp2#176]
trying to install on Raspberry Pi running Ubuntu 18.04.4 LTS with all updates/upgrades applied

Notice initial warnings about 
TASK [Stouts.postfix : Install requirements (Debian)] *******************************************************************************************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple items and specifying `name: "{{item}}"`, please use `name: ['postfix', 
'ca-certificates', 'mailutils', 'libsasl2-modules']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [wifi.wrennall.co.uk] => (item=[u'postfix', u'ca-certificates', u'mailutils', u'libsasl2-modules'])

but the actual fatal error is as follows
TASK [openwisp.openwisp2 : Install cryptography from pip] ***************************************************************************************************************************************************************
FAILED - RETRYING: Install cryptography from pip (5 retries left).
FAILED - RETRYING: Install cryptography from pip (4 retries left).
FAILED - RETRYING: Install cryptography from pip (3 retries left).
FAILED - RETRYING: Install cryptography from pip (2 retries left).
FAILED - RETRYING: Install cryptography from pip (1 retries left).
fatal: [xxxxxxxxxx]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/opt/openwisp2/env/bin/pip3", "install", "-U", "cryptography"], "msg": "stdout: Collecting cryptography\n  Using cached cryptography-2.9.tar.gz (517 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n    Preparing wheel metadata: started\n    Preparing wheel metadata: finished with status 'error'\n\n:stderr:     ERROR: Command errored out with exit status 1:\n     command: /opt/openwisp2/env/bin/python3 /opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpo00x0d9x\n         cwd: /tmp/pip-install-xqx89o1t/cryptography\n    Complete output (40 lines):\n    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'\n      warnings.warn(msg)\n    Traceback (most recent call last):\n      File \"/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py\", line 257, in <module>\n        main()\n      File \"/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py\", line 240, in main\n        json_out['return_val'] = hook(**hook_input['kwargs'])\n      File \"/opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py\", line 110, in prepare_metadata_for_build_wheel\n        return hook(metadata_directory, config_settings)\n      File \"/usr/lib/python3/dist-packages/setuptools/build_meta.py\", line 113, in prepare_metadata_for_build_wheel\n        _run_setup()\n      File \"/usr/lib/python3/dist-packages/setuptools/build_meta.py\", line 72, in _run_setup\n        exec(compile(code, __file__, 'exec'), locals())\n      File \"setup.py\", line 274, in <module>\n        **keywords_with_side_effects(sys.argv)\n      File \"/usr/lib/python3/dist-packages/setuptools/__init__.py\", line 129, in setup\n        return distutils.core.setup(**attrs)\n      File \"/usr/lib/python3.6/distutils/core.py\", line 108, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 372, in __init__\n        _Distribution.__init__(self, attrs)\n      File \"/usr/lib/python3.6/distutils/dist.py\", line 281, in __init__\n        self.finalize_options()\n      File \"/usr/lib/python3/dist-packages/setuptools/dist.py\", line 528, in finalize_options\n        ep.load()(self, ep.name, value)\n      File \"/tmp/pip-build-env-ocvnhnu9/overlay/lib/python3.6/site-packages/cffi/setuptools_ext.py\", line 217, in cffi_modules\n        add_cffi_module(dist, cffi_module)\n      File \"/tmp/pip-build-env-ocvnhnu9/overlay/lib/python3.6/site-packages/cffi/setuptools_ext.py\", line 49, in add_cffi_module\n        execfile(build_file_name, mod_vars)\n      File \"/tmp/pip-build-env-ocvnhnu9/overlay/lib/python3.6/site-packages/cffi/setuptools_ext.py\", line 25, in execfile\n        exec(code, glob, glob)\n      File \"src/_cffi_src/build_openssl.py\", line 122, in <module>\n        extra_link_args=extra_link_args(compiler_type()),\n      File \"src/_cffi_src/utils.py\", line 57, in build_ffi_for_binding\n        extra_link_args=extra_link_args,\n      File \"src/_cffi_src/utils.py\", line 65, in build_ffi\n        ffi = FFI()\n      File \"/tmp/pip-build-env-ocvnhnu9/overlay/lib/python3.6/site-packages/cffi/api.py\", line 56, in __init__\n        backend.__version__, backend.__file__))\n    Exception: Version mismatch: this is the 'cffi' package version 1.14.0, located in '/tmp/pip-build-env-ocvnhnu9/overlay/lib/python3.6/site-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.11.5, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-36m-arm-linux-gnueabihf.so'.  The two versions should be equal; check your installation.\n    ----------------------------------------\nERROR: Command errored out with exit status 1: /opt/openwisp2/env/bin/python3 /opt/openwisp2/env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpo00x0d9x Check the logs for full command output.\n"}

does this need apt-get install python-cffi ?

**Comment by nemesisdesign** [comment]
Seems a not unusual system issue: https://stackoverflow.com/questions/43325110/exception-version-mismatchcffi.

It's not showing up in brand new ubuntu VMs though, since this role is being tested automatically on travis on Ubuntu 18, hence you have to fix this manually, I suggest trying as suggested in the link above.

**Comment by nemesisdesign** [comment]
I'm closing since it shouldn't be a bug (because it doesn't show up in the automated build) but you can keep asking questions if you need.

**Comment by nemesisdesign** [comment]
PS: if you need help you can also look here: http://openwisp.org/support.html
