### ISSUE TITLE
[bug] Install fail on debian 10

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#177]
A user reported on Gitter channel that installing on debian 10 cases an issue:
```
TASK [openwisp.openwisp2 : Remove jsonfield2] **
FAILED - RETRYING: Remove jsonfield2 (2 retries left).
FAILED - RETRYING: Remove jsonfield2 (1 retries left).
fatal: [(mydomain)]: FAILED! => {"attempts": 2, "changed": false, "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}

RUNNING HANDLER [Stouts.postfix : postfix restart] *

RUNNING HANDLER [openwisp.openwisp2 : reload systemd] **

RUNNING HANDLER [openwisp.openwisp2 : start redis] *

PLAY RECAP *
(mydomain) : ok=21 changed=11 unreachable=0 failed=1 skipped=25 rescued=0 ignored=0
```

Need to verify and fix it. :smile:

**Comment by pniaps** [comment]
The same error with a fresh install of centos 7 in a VPS

```
TASK [openwisp.openwisp2 : Remove jsonfield2] **************************************************************************************************
FAILED - RETRYING: Remove jsonfield2 (2 retries left).
FAILED - RETRYING: Remove jsonfield2 (1 retries left).
fatal: [(mydomain)]: FAILED! => {"attempts": 2, "changed": false, "msg": "Failed to find required executable virtualenv in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin"}

RUNNING HANDLER [Stouts.postfix : postfix restart] *********************************************************************************************

PLAY RECAP *************************************************************************************************************************************
(mydomain)            : ok=9    changed=4    unreachable=0    failed=1    skipped=37   rescued=0    ignored=0   

```

**Comment by pniaps** [comment]
My fault, CentOS is not supported.

**Comment by nemesisdesign** [comment]
@pniaps are you getting this problem elsewhere? If yes can you paste the contents of `/etc/issue` please?

**Comment by pniaps** [comment]
No, it worked on Ubuntu 18.04

**Comment by nemesisdesign** [comment]
I'm glad it worked @pniaps, it should also work on ubuntu 20 if you use this branch: https://github.com/openwisp/ansible-openwisp2/tree/ubuntu20

**Comment by miff2000** [comment]
I can't replicate this issue in my environment, but the error is complaining about the virtualenv being missing.

This is defined [here](https://github.com/openwisp/ansible-openwisp2/blob/ea8ad58/vars/main.yml#L1):
```yaml
virtualenv_path: "{{ openwisp2_path }}/env"
```

That in turn is defined [here](https://github.com/openwisp/ansible-openwisp2/blob/ea8ad58/defaults/main.yml#L19):
```yaml
openwisp2_path: "/opt/openwisp2"
```

However, the `openwisp2_path` directory is not created until _after_ `pip.yml` runs, by `django.yml`.

So the fix to me seems to be to move that directory creation step to the `pip.yml` include.

@atb00ker, could you re-rest this using this fork to see if it does fix the issue?
* https://github.com/miff2000/ansible-openwisp2

**Comment by miff2000** [comment]
Tried to replicate using Vagrant with `debian/buster64` box and it completed without error also.

Regardless however, moving creation of the path to occur earlier in the role still makes sense.
Permissions look correct when the role has finished still:
```yaml
- name: Create {{ openwisp2_path }}
  file:
    path: "{{ openwisp2_path }}"
    state: directory
    group: "{{ www_group }}"
    mode: 0775
```
```shell
vagrant@buster:~$ ls -ald /opt/openwisp2/
drwxrwxr-x 8 root www-data 4096 Oct  3 17:11 /opt/openwisp2/
```

**Comment by nemesisdesign** [comment]
Closing this issue because it cannot be replicated.
