### ISSUE TITLE
Installation failure on Ubuntu 18.04

### ISSUE THREAD

**Issue by kanthans** [openwisp/ansible-openwisp2#178]
Hi
Installed on Ubuntu 18.04 server, fresh installation. However the ansible script failed with the following error. 

fatal: [openwisp.sbalab.com]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput", "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/django/core/management/__init__.py\", line 401, in execute_from_command_line\n    utility.execute()\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/django/core/management/__init__.py\", line 377, in execute\n    django.setup()\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/django/__init__.py\", line 24, in setup\n    apps.populate(settings.INSTALLED_APPS)\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/django/apps/registry.py\", line 91, in populate\n    app_config = AppConfig.create(entry)\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/django/apps/config.py\", line 116, in create\n    mod = import_module(mod_path)\n  File \"/opt/openwisp2/env/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 994, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 665, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/channels/apps.py\", line 6, in <module>\n    import daphne.server\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/daphne/server.py\", line 5, in <module>\n    from twisted.internet import asyncioreactor  # isort:skip\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py\", line 16, in <module>\n    from twisted.internet.base import DelayedCall\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/twisted/internet/base.py\", line 27, in <module>\n    from twisted.internet._resolver import (\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/twisted/internet/_resolver.py\", line 25, in <module>\n    from twisted.internet.address import IPv4Address, IPv6Address\n  File \"/opt/openwisp2/env/lib/python3.6/site-packages/twisted/internet/address.py\", line 101, in <module>\n    @attr.s(hash=False, repr=False, eq=False)\nTypeError: attrs() got an unexpected keyword argument 'eq'\n", "path": "/opt/openwisp2/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin", "syspath": ["/tmp/ansible_django_manage_payload_k4qt1zf9/ansible_django_manage_payload.zip", "/usr/lib/python36.zip", "/usr/lib/python3.6", "/usr/lib/python3.6/lib-dynload", "/usr/local/lib/python3.6/dist-packages", "/usr/lib/python3/dist-packages"]}

**Comment by kanthans** [comment]
Found the issue to be attrs version. Manually upgraded the attrs version in the python environment using pip3 install --upgrade attrs from 17.4.0 to 19.3.0. Then ran the ansible script from the ansible system. The installation completed successfully. 

We got the login page but unable to login with admin/admin. 

Verified the /opt/openwisp2/log/openwisp2.log file. It showed unable to write to the db. The db file, db.sqlite3 in /opt/openwisp2 is with owner permission as root. Changed the linux ownership to www-data. Able to successfully login. 

This is my first attempt with both openwrt and openwisp. Let me give a feedback after using.

**Comment by nemesisdesign** [comment]
Thanks a lot for reporting @kanthans. 
The problem with the attrs python package should not happen, I got a similar report just recently.
I will re-open the issue, I think we can get the ansible role to upgrade the package.
It's a shame that the travis build is not catching this issue.

**Comment by nemesisdesign** [comment]
@kanthans it was reported to me that the user who was having the same problem as you solved by forcing the ansible python interpreter to be python3 (on some system python2.7 may be used by default).
I thought by default python3 would be used. If that's the case we'd have to point this in the README.
If you could try and let me know it would be helpful, thanks.

**Comment by kanthans** [comment]
1. Installed fresh installation of Ubuntu server 18.04, set python3 as the default using 
`update-alternatives --install /usr/bin/python python /usr/bin/python3`
2. Ran the ansible script  and faced the same issue
3. Verified default python version in ubuntu, it is python3
4. Before running the script, the system did not had python2, however after running the script it had python2.7, which I think is part of the prerequisite.
5. While the proposed openwisp system runs ubuntu 18.04, my ansible system is running on Centos 7.7 - Does that matter?

**Comment by atb00ker** [comment]
1. You are using `Ubuntu server 18.04` but supported distro is `Ubuntu 18.04`. I am not sure if it makes a difference though -- just noted a difference.
2. Depending on your ansible version, you may need to force ansible to use python3, `ansible_python_interpreter=/usr/bin/python3`

**Comment by nemesisdesign** [comment]
I have replicate the `attrs` error on vagrant-openwisp2 using ubuntu 18.

I also have created an issue regarding the fact that our automated tests are not catching these issues: https://github.com/openwisp/ansible-openwisp2/issues/179

**Comment by nemesisdesign** [comment]
@kanthans this change fixes it: https://github.com/openwisp/ansible-openwisp2/pull/180

Please try when you can and let us know!
