### ISSUE TITLE
[feature] Add possibility to restrict access to admin to specified ip ranges

### ISSUE THREAD

**Issue by hscadore** [openwisp/ansible-openwisp2#18]
Sometimes admins don't need or prefer not to have access to the management console of a controller from an untrusted network, although they will still want clients to connect to the controller and get configurations from these same untrusted netwoks. I suggest a role variable which would enable admins to restrict access to the management console allowing only computers from trusted networks to do so while Openwrt/LEDE clients from trusted and untrusted networks will still be able to work with Openwisp. This would improve security reducing the surface of attacks such as weak passwords and possibly other types of attacks.

**Comment by nemesisdesign** [comment]
Some instructions regarding how to implement this have been written here:
https://groups.google.com/d/msg/openwisp/0IHj9TQjegk/yThGaxNoBgAJ

**Comment by nemesisdesign** [comment]
@hscadore implemented in 4272db8
