### ISSUE TITLE
[DEPRECATION WARNING]: evaluating 'openwisp2_python_packages' as a bare  variable

### ISSUE THREAD

**Issue by hispanico** [openwisp/ansible-openwisp2#182]
Fix statement condition on "Install custom OpenWISP 2 Python packages" task in pip.yml:

```bash
TASK [openwisp.openwisp2 : Install custom OpenWISP 2 Python packages] **********
[DEPRECATION WARNING]: evaluating 'openwisp2_python_packages' as a bare 
variable, this behaviour will go away and you might need to add |bool to the 
expression in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. 
```

**Comment by nemesisdesign** [comment]
@hispanico thanks for bringing this up, I added it to the [Google Code-In project board](https://github.com/orgs/openwisp/projects/12#card-37651560).

**Comment by dwang** [comment]
This was fixed here: https://github.com/openwisp/ansible-openwisp2/commit/23d476acba8b684133653161289c2ff54be8c557#diff-9bdb1bd6974cb2b2838d95ce7cf3f63e0996b9544f42fb0f216557eb68424d6aR126

I just tested and there aren't any other deprecation warnings.

**Comment by nemesisdesign** [comment]
Thanks for reporting @dwang!
