### ISSUE TITLE
[gsoc2020] Merged Modules remove django-netjsongraph 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#185]
After https://github.com/openwisp/openwisp-network-topology/pull/63 is merged, remove django-netjsongraph from ansible-openwisp2.

**Comment by nemesisdesign** [comment]
@atb00ker tip: perform a search of django-netjsongraph in the whole repo when you do this (forgive me for the obvious tip but sometimes we all forget to do these simple things)
We'll need to issue a new release of openwisp-network-topology and increase the version in this file: https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml#L4
