### ISSUE TITLE
Internal Server Error after Installation

### ISSUE THREAD

**Issue by adamnotfound** [openwisp/ansible-openwisp2#191]
I had openwisp2 installed on a remote linux server, but now I'm getting Internal Server Error when I try to visit my openwisp2 domain.
I tried to do reproduce using the ansible-playbook but still getting same error.

**Comment by hispanico** [comment]
Could you post the openwisp logs: /opt/openwisps2/log/*.log

**Comment by nemesisdesign** [comment]
@adamnotfound try:

```
chown -R www-data:www-data /opt/openwisp2/logs
chown -R www-data:www-data /opt/openwisp2/static
supervisorctl restart all
```

and let me know if it fixes it.

**Comment by adamnotfound** [comment]
> @adamnotfound try:
> 
> ```
> chown -R www-data:www-data /opt/openwisp2/logs
> chown -R www-data:www-data /opt/openwisp2/static
> supervisorctl restart all
> ```
> 
> and let me know if it fixes it.

It doesn't fix the problem, and that's what I'm getting when I tried what you mentioned

`daphne:asgi1: stopped
daphne:asgi0: stopped
daphne:asgi2: stopped
celery: stopped
celery: started
daphne:asgi1: started
daphne:asgi0: started
daphne:asgi2: started
openwisp2: ERROR (spawn error)
`

**Comment by adamnotfound** [comment]
> Could you post the openwisp logs: /opt/openwisps2/log/*.log

Do you want me to post all the log files or openwisp2.log only ?

**Comment by nemesisdesign** [comment]
@adamnotfound in your logs (celery and daphne) I see:

```
'schedule': timedelta(minutes=5),
NameError: name 'timedelta' is not defined
```

But I [can't find any occurrences of timedelta in this ansible role](https://github.com/openwisp/ansible-openwisp2/search?q=timedelta&unscoped_q=timedelta), it must be something that is added via configuration or customization.

That is surely causing an issue, although I can't be sure if that's what's blocking your application from working altogether.

The log of the web app (openwisp2.log) looks fine, but the uwsgi log says you have another instance of uwsgi (the application server) running, therefore it won't start. Looks like you have some zombie process running:

```
probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
bind(): Address already in use [core/socket.c line 769]
```

Do `supervisorctl stop all` and kill any openwisp related process that is in zombie state, then start again.

**Comment by adamnotfound** [comment]
@nem

> @adamnotfound in your logs (celery and daphne) I see:
> 
> ```
> 'schedule': timedelta(minutes=5),
> NameError: name 'timedelta' is not defined
> ```
> 
> But I [can't find any occurrences of timedelta in this ansible role](https://github.com/openwisp/ansible-openwisp2/search?q=timedelta&unscoped_q=timedelta), it must be something that is added via configuration or customization.
> 
> That is surely causing an issue, although I can't be sure if that's what's blocking your application from working altogether.
> 
> The log of the web app (openwisp2.log) looks fine, but the uwsgi log says you have another instance of uwsgi (the application server) running, therefore it won't start. Looks like you have some zombie process running:
> 
> ```
> probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
> bind(): Address already in use [core/socket.c line 769]
> ```
> 
> Do `supervisorctl stop all` and kill any openwisp related process that is in zombie state, then start again.

@nemesisdesign 
I did supervisorctl stop all and ran ansible-playbook command again but still running in the same issue.
Is there anyway I can uninstall openwisp related dependencies and services and try to install it all again then show you the logs if the issue is still there ?

**Comment by nemesisdesign** [comment]
> > @adamnotfound in your logs (celery and daphne) I see:
> > ```
> > 'schedule': timedelta(minutes=5),
> > NameError: name 'timedelta' is not defined
> > ```
> > 
> > 
> > But I [can't find any occurrences of timedelta in this ansible role](https://github.com/openwisp/ansible-openwisp2/search?q=timedelta&unscoped_q=timedelta), it must be something that is added via configuration or customization.
> > That is surely causing an issue, although I can't be sure if that's what's blocking your application from working altogether.
> > The log of the web app (openwisp2.log) looks fine, but the uwsgi log says you have another instance of uwsgi (the application server) running, therefore it won't start. Looks like you have some zombie process running:
> > ```
> > probably another instance of uWSGI is running on the same address (127.0.0.1:3031).
> > bind(): Address already in use [core/socket.c line 769]
> > ```
> > 
> > 
> > Do `supervisorctl stop all` and kill any openwisp related process that is in zombie state, then start again.
> 
> @nemesisdesign
> I did supervisorctl stop all and ran ansible-playbook command again but still running in the same issue.
> Is there any way I can uninstall openwisp related dependencies and services and try to install it all again then show you the logs if the issue is still there ?

@adamnotfound sorry for the late reply, to uninstall, delete `/opt/openwisp2` and `/etc/supervisor/conf.d/*` and run the playbook again.

I'm closing this issue now, but feel free to ask more questions if you need, here or in the [support channels](http://openwisp.org/support.html).
if it's a bug we'll reopen.
