### ISSUE TITLE
Documentation: How to uninstall

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/ansible-openwisp2#192]
I followed the installation guide for testing purposes and successfully installed openwisp in my raspberry pi. Now I would like to uninstall it. How should I proceed?

So far I have:

* Remove: `/opt/openwisp2`, `/etc/supervisor`, `/etc/nginx/`
* Uninstalled: `nginx`, `postfix`, `redis-server` and `supervisor`

**Comment by nemesifier** [comment]
Unfortunately, keeping track of the uninstall process is expensive and we don't have bandwidth for it.
That's why we suggest using virtual machines.
The right steps to uninstall can be figured out by looking at the ansible role, if needed.
