### ISSUE TITLE
[feature] Add support for openwisp-firmware-upgrader

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#199]
We can install this module by default and enable its API, we can provide a variable to disable the module and another variable to disable only the API if needed.

**Comment by pandafy** [comment]
@nemesisdesign I don't see a potential use for creating a dedicated variable for disabling just APIs. The users can simple enable or disable APIs using by setting `OPENWISP_FIRMWARE_UPGRADER_API` in 'openwisp2_extra_django_settings' variable.

**Comment by nemesisdesign** [comment]
> @nemesisdesign I don't see a potential use for creating a dedicated variable for disabling just APIs. The users can simple enable or disable APIs using by setting `OPENWISP_FIRMWARE_UPGRADER_API` in `openwisp2_extra_django_settings` variable.

Agreed, what about a brief section for the firmware upgrader module in the README like we have for [network topology](https://github.com/openwisp/ansible-openwisp2#enabling-the-network-topology-module)?
In that section we could advise this (that API can be disabled this way, as well as setting other settings and link to the firmware upgrader settings).

**Comment by pandafy** [comment]
I have [added it in the PR](https://github.com/openwisp/ansible-openwisp2/pull/221/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R431-R476 ) :smile:
