### ISSUE TITLE
[feature] Automatically create default SSH credentials

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#200]
Feature needed to make push updates and firmware-upgrader work out of the box #199 

If there are no other credentials generated in the system:

- Automatically generate an SSH private key / public key pair
- Create a credentials object with root and the private key created, flag it as `auto_add=True`
- Look if there is any template flagged as default which contains /etc/dropbear/authorized_keys, if there is, append the public key to it, if there isn't, create one and flag it as default

**Comment by pandafy** [comment]
I am working on it! :smile:

**Comment by iantait** [comment]
This feature seems to overwrite any existing keys on a new device install?

**Comment by nemesisdesign** [comment]
> This feature seems to overwrite any existing keys on a new device install?

A template is created only if there's no other template defining `/etc/dropbear/authorized_keys`.
If no template is defined, yes, local authorized keys will be overwritten, add those to the template, removing the template may work as well (previous backed up file should be restored) but please ensure you have another way to access the device before trying it.
