### ISSUE TITLE
Fresh Install of OpenWisp Produces 502 error on admin page

### ISSUE THREAD

**Issue by do0zer** [openwisp/ansible-openwisp2#202]
This problem occurs in both Debian 10 and Ubuntu 18.04

Not doing anything fancy just attempting a plain vanilla install.

Any help would be appreciated

Using a plain playbook:

- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"

with this in the hosts: with my url

[openwisp2]
openwisp2.mydomain.com

And successfully running 

ansible-playbook -i hosts playbook.yml -u ansible -k --become -K

The admin page produces a 502 Bad gateway

The nginx error log produces:

2020/08/27 06:25:54 [error] 15584#15584: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 47.32.121.71, server: myhost.com, request: "GET /admin HTTP/1.1", upstream: "uwsgi://127.0.0.1:3031", host: "myhost.com"

**Comment by nemesisdesign** [comment]
it may be related to this issue: https://github.com/openwisp/ansible-openwisp2/issues/85, but I'm not 100% sure.

Try the following:

```
sudo -s
supervisorctl stop all
chown www-data:www-data -R /opt/openwisp2/log
chown www-data:www-data -R /opt/openwisp2/static
# check if there's any zombie uwsgi process, kill everything you find
supervisorctl start all
```

**Comment by do0zer** [comment]
That did not seem to resolve the problem.

Thanks for the suggestion

**Comment by do0zer** [comment]
I think you gave me enough of a lead to get the problem sorted

also doing: chown www-data:www-data -R /opt/openwisp2/ has seemed to resolve my issue

Thanks for the help!

**Comment by nemesisdesign** [comment]
Glad it helped. I hope we'll be able to solve this and avoid it in the first place.

**Comment by deykmora** [comment]
> puede estar relacionado con este problema:  [# 85](https://github.com/openwisp/ansible-openwisp2/issues/85) , pero no estoy 100% seguro.
> 
> Intente lo siguiente:
> 
> ```
> sudo -s
> supervisorctl stop all
> chown www-data:www-data -R /opt/openwisp2/log
> chown www-data:www-data -R /opt/openwisp2/static
> # check if there's any zombie uwsgi process, kill everything you find
> supervisorctl start all
> ```

**Comment by deykmora** [comment]
Hola donde colocaria esto?
