### ISSUE TITLE
[docs] Instructions on how to run tests outdated

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#208]
It seems the instructions on how to run tests are outdated: https://github.com/openwisp/ansible-openwisp2#how-to-run-tests.

Ideally we should have a simpler section with less steps, I hope we can do that.

**Comment by nemesisdesign** [comment]
@hispanico @PabloCastellano can I ask a hint about how to update that section?

**Comment by atb00ker** [comment]
If docker and ansible-openwisp2 are already setup, we can start from step 4,
in step 4, `<name>` can be hardcoded.

It might be possible to run step 5 & 6 from docker image itself by adding a bash script in the docker container that runs when docker image is run.

That's at the top of my head presently.

**Comment by hispanico** [comment]
I think the easy way is to include a molecule scenario for local test and write down the instruction to install and run molecule locally.
