### ISSUE TITLE
[feature] Add openwisp-notifications

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#214]
- automatically set site domain using the FQDN (by default is example.com and the notification JS widget will send users to example.com if not set correctly) and add suggestion to revise this manually once the installation is completed
  - ensure the [settings for the notifications module are present](https://github.com/openwisp/openwisp-controller/pull/265/files#diff-9dec27df1ed1039b50d2b96520f1de08)

This is required to release openwisp-controller 0.8.

**Comment by pandafy** [comment]
I am working on it. :smile:

**Comment by pandafy** [comment]
> * automatically set site domain using the FQDN (by default is example.com and the notification JS widget will send users to example.com if not set correctly) and add suggestion to revise this manually once the installation is completed

I believe this has been already implemented in [_create load_initial_data.py script_ tasks in openwisp.openwisp2/tasks/django.yml](https://github.com/openwisp/ansible-openwisp2/blob/master/tasks/django.yml#L123-L127).

Here is the code responsible for bringing that change:

https://github.com/openwisp/ansible-openwisp2/blob/8ef2809ed9014b3420dd326426e0a1eb142ec30b/templates/load_initial_data.py#L24-L31

We will just need to add following as it has been done with "change password for admin user"

1. Documentation to update the setting once the the playbook has run successfully. 
2. A message in the playbook asking the user to update the settings.

------------------

While adding openwisp_notifications, I think adding dedicated variables in Ansible role for configuring options of the notifications modules will only bloat the role. It will be safe to leave them to user to use `openwisp2_extra_django_settings_instructions` variable for using them.
