### ISSUE TITLE
[docs] Ambiguous development instructions

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-openwisp2#217]
Documentation for installing the project for development asks the user to clone the project as follows
```
git clone https://github.com/openwisp/ansible-openwisp2.git openwisp.openwisp2
```

On the other hand, instructions for running tests in the development environment asks to clone the project as follows:
```
git clone https://github.com/<your_fork>/ansible-openwisp2.git
```

I think the former is done to [reuse the instructions for creating playbook given for end users](https://github.com/openwisp/ansible-openwisp2#create-playbook-file) while the latter is done to make tests work on Travis since it clones the project with the name of the project.
 
`ansible-openwisp2/molecule/resources/converge.yml` also uses ` ansible-openwisp2` role instead of `openwisp.openwisp2`

https://github.com/openwisp/ansible-openwisp2/blob/8ef2809ed9014b3420dd326426e0a1eb142ec30b/molecule/resources/converge.yml#L20-L21

I followed the first instruction only to find out that the test suite is not running. I had to manually fix above file to run tests. 

It will be in the best interest to remove this ambiguity and use the same role for everything.

**Comment by nemesisdesign** [comment]
Shall we always suggest using the fork? Only a minority of contributors will be using the main repository.

@pandafy @hispanico @atb00ker what do you think?

**Comment by atb00ker** [comment]
This "How to test" part & module tests one was written much later, hence the difference, I think we can do with 
```
git clone https://github.com/<your_fork>/ansible-openwisp2.git openwisp.openwisp2
```

(Using fork but naming it `openwisp.openwisp2`)

**Comment by pandafy** [comment]
@atb00ker if you clone the repository in `openwisp.openwisp2` directory then the tests will fail until you update the following to use `openwisp.openwisp2` role.

https://github.com/openwisp/ansible-openwisp2/blob/8ef2809ed9014b3420dd326426e0a1eb142ec30b/molecule/resources/converge.yml#L20-L21

This was my main concern

**Comment by atb00ker** [comment]
@pandafy A simple syslink should take care of that, I suppose. :smile:

**Comment by unnati914** [comment]
hey!
could I work on this?

**Comment by Aryamanz29** [comment]
Hey @pandafy, Is this issue still relevant?  After merging of https://github.com/openwisp/ansible-openwisp2/pull/381, `ansible-openwisp2/molecule/resources/converge.yml` looks like this :
https://github.com/openwisp/ansible-openwisp2/blob/b348970d49785203635562cba75a407f3b154cc2/molecule/resources/converge.yml#L25-L26
I think now we can update `README` as well. What do you think?

**Comment by Aryamanz29** [comment]
> This "How to test" part & module tests one was written much later, hence the difference, I think we can do with
> 
> ```
> git clone https://github.com/<your_fork>/ansible-openwisp2.git openwisp.openwisp2
> ```
> 
> (Using fork but naming it `openwisp.openwisp2`)

We can now do this change.

**Comment by pandafy** [comment]
> > This "How to test" part & module tests one was written much later, hence the difference, I think we can do with
> > ```
> > git clone https://github.com/<your_fork>/ansible-openwisp2.git openwisp.openwisp2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (Using fork but naming it `openwisp.openwisp2`)
> 
> We can now do this change.

You can go ahead with this @Aryamanz29

**Comment by Aryamanz29** [comment]
> > > This "How to test" part & module tests one was written much later, hence the difference, I think we can do with
> > > ```
> > > git clone https://github.com/<your_fork>/ansible-openwisp2.git openwisp.openwisp2
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > (Using fork but naming it `openwisp.openwisp2`)
> > 
> > We can now do this change.
> 
> You can go ahead with this @Aryamanz29 

Thanks for confirming 👍
