### ISSUE TITLE
[bug] Idempotence tests for "Install custom OpenWISP 2 Python packages" task

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-openwisp2#218]
installing a python package using pip through a URLs will always install it irrespective of the fact that whether it has been already installed or not. 

While testing the role for development version of the module using URLs for their GitHub repositories, the idempotence test fails. 

I think it will be in the best interest to disable skip idempotence test for following task, because it is supposed to install packages from URLs only. 

https://github.com/openwisp/ansible-openwisp2/blob/8ef2809ed9014b3420dd326426e0a1eb142ec30b/tasks/pip.yml#L141-L154

**Comment by nemesisdesign** [comment]
Ok we can skip it :+1:
