### ISSUE TITLE
APT only support is not ideal 

### ISSUE THREAD

**Issue by AndreaFerraresi** [openwisp/ansible-openwisp2#240]
Hi guys, I was going through the ansible module of OpenWISP and I realized that it is apt only. This is not really ideal, especially if you want to use this system on enterprise-grade situations. 
The code should be supported on redhat/fedora/centos as well. An alternative would be using Package instead of APT or, if it isn't possible, we should be using yum. 

Will try to work on this during my holidays and give you some feedbacks

**Comment by nemesisdesign** [comment]
@AndreaFerraresi we used to support Redhat distros, but we don't have the resources to maintain it. It was slowing us down.
We'll migrate to [docker-openwisp](https://github.com/openwisp/docker-openwisp) anyway as soon as possible so I do not suggest investing in this effort.

Those who do need Redhat can start from this branch and update it as they need: https://github.com/openwisp/ansible-openwisp2/pull/151.

**Comment by AndreaFerraresi** [comment]
Just my two cents: Ansible can also be used for kubernetes operators, with docker changing the license and openshift going away from it I would be careful on investing time in docker-compose as well.

But let me know if I can help

**Comment by nemesisdesign** [comment]
@AndreaFerraresi check this out: https://github.com/openwisp/docker-openwisp/blob/master/docker-compose.yml

These are the priorities we're working on: https://github.com/orgs/openwisp/projects/4
The current goal is to get to a point in which the main modules are all robust, ship the most requested features, installable via ansible and decently documented.
