### ISSUE TITLE
[bug] HTML minification issue: <pre> tags should not be minified

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#256]
The DRF browsable API interface formatting breaks with HTML minification enabled.

![Screenshot from 2021-01-21 12-58-30](https://user-images.githubusercontent.com/841044/105391737-6af65180-5be8-11eb-8e2e-699dee3e5b3a.png)

I opened an issue in django-pipeline: https://github.com/jazzband/django-pipeline/issues/744.

**Comment by nemesisdesign** [comment]
Has been fixed by https://github.com/openwisp/openwisp-utils/pull/198.

This issue can be closed once openwisp-utils 0.7.5 is released: https://github.com/openwisp/openwisp-utils/issues/201.

**Comment by pandafy** [comment]
openwisp-utils 0.7.5 is released: https://github.com/openwisp/openwisp-utils/releases/tag/0.7.5
