### ISSUE TITLE
Installing OpenWISP on OpenWRT

### ISSUE THREAD

**Issue by nsmith1024** [openwisp/ansible-openwisp2#258]
Hello,

I have OpenWRT that i built myself for Raspberry PI. I want to use it with OpenWISP.

Is OpenWISP a package in OpenWRT so that i can use "opkg install wisp2", or how do i install it on there?

Can i built it into the firmware using "make menuconfig" selecting it from the menu, and then "make"

We have a HUGE project at work we are thinking of using OpenWISP2 for it.

Thanks

**Comment by nemesisdesign** [comment]
Please read https://openwisp.io/docs/user/configure-device.html carefully.
For further questions use the support channels (general chat or ML): https://openwisp.org/support.html

**Comment by nsmith1024** [comment]
That link doesnt work, it said secure connection failed, and the browser wont let me see it.

**Comment by nemesisdesign** [comment]
@nsmith1024 works fine on my end and works fine in the google cache.
