### ISSUE TITLE
OpenWISP connection method to agent

### ISSUE THREAD

**Issue by nsmith1024** [openwisp/ansible-openwisp2#260]
Hello,

I was in the OpenWISP chat room, and someone mentioned that how it works is that there is an OpenWISP agent that resides on the OpenWRT router. That agent connects to the django app,  that app is the main app thats configuring the router.

We are thinking of using OpenWISP for our project, but we would like if it worked the other way, where the django app connects to the OpenWISP agent in the router.

so instead of  agent --> django we need it to work like agent <--- django

is this possible? our router runs on batteries so we can have it constantly polling and trying to connect to the django app, so we want the agent on the OPenWRT router to just sit and listen for connections from django

Please let me know if this is possible.

Thanks

**Comment by okraits** [comment]
For general questions use the support channels (general chat or ML): https://openwisp.org/support.html
