### ISSUE TITLE
ERROR! couldn't resolve module/action 'django_manage'.

### ISSUE THREAD

**Issue by VM-2020** [openwisp/ansible-openwisp2#261]
Following the installation instructions I got this error message when running the playbook.
I installed Ansible on Manjaro (Arch-linux) from the repo package installer..

The error appears to be in '/root/.ansible/roles/openwisp.openwisp2/tasks/django.yml': line 104, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: migrate
  ^ here

**Comment by maansiii** [comment]
Try to upgrade the Ansible and see if it works.

**Comment by VM-2020** [comment]
Hi, thanks for replying..

I have figured it out in the end - did use ansible-base first but this is only for dev.
Installed the full package and could continue with installing OpenWISP..

Finally had to change ansible.cfg - and changed #host_key_checking= True > False

Also got some [DEPRECATION WARNINGS] on Stouts.postfix: Install requirements (Debian) and Install DKIM requirements (Debian)

**Comment by VM-2020** [comment]
Just an remark, about installing Certs/LetsEncrypt..

I had to make some changes getting it done because it was challenging (ACME) the wrong domain.
The install is done on a VPS with loop-back domains (127.0.1.1) of the hosting provider, eg. domain.colo.hostingprovider.net

- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - thefinn93.letsencrypt
    - openwisp.openwisp2
  vars:
    # SSL certificates
    openwisp2_ssl_cert: "/etc/letsencrypt/live/**<FQDN_HERE>**/fullchain.pem"
    openwisp2_ssl_key: "/etc/letsencrypt/live/**<FQDN_HERE>**/privkey.pem"
    # letsencrypt configuration
    letsencrypt_webroot_path: "{{ openwisp2_path }}/public_html"
    letsencrypt_email: <YOUR_EMAIL_HERE>
    **letsencrypt_cert_domains:
        - www.example.net
        - example.net**
    letsencrypt_renewal_command_args: '--renew-hook "**systemctl restart nginx**"'
    letsencrypt_renewal_frequency:
      day: "*"
      hour: "7,19"  # renewal cronjob runs at 7 AM and at 7 PM
      minute: 0

**Comment by nemesisdesign** [comment]
Thanks for sharing, please use the support channels if you need more help: https://openwisp.org/support.html
This is the bug tracker.
