### ISSUE TITLE
[chores] Remove workaround for a excluding leaflet icon from static minification

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-openwisp2#266]
#238 introduced a workaround to enable excluding files from minification and versioning because of #232 

Since, that functionality has been ported in openwisp-utils in https://github.com/openwisp/openwisp-utils/pull/172 (to simplify maintenance), we can remove the workaround from the ansible role and update the settings accordingly. 

Let's send a patch to dev branch.

**Comment by nemesisdesign** [comment]
@pandafy do you confirm that this issue is unblocked now?

**Comment by pandafy** [comment]
This requires openwisp-utils 0.8.0. I have updated the issue description as well.

**Comment by Arsh0023** [comment]
Can I start working on this?

**Comment by pandafy** [comment]
We can start working on this now as the role installs OpenWISP modules from GitHub.

**Comment by totallynotvaishnav** [comment]
@pandafy do you suggest removing `storage.py` completely as it already has been ported to openwisp-utils?

https://github.com/openwisp/ansible-openwisp2/blob/0e6edf251dd9fa9fc825a75df42f80dd8dee530c/files/storage.py#L10-L23

should this be handled in openwisp-utils?

**Comment by pandafy** [comment]
@totallynotvaishnav good catch. Yes, we will need to port this workaround to openwisp-utils. 

https://github.com/openwisp/ansible-openwisp2/blob/0e6edf251dd9fa9fc825a75df42f80dd8dee530c/files/storage.py#L10-L23

The storage backend is present in [openwisp_utils/storage.py](https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/storage.py)
