### ISSUE TITLE
[change] Update nginx max file upload size to match firmware upgrader

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#269]
If firmware upgrader is enabled, we should increase the default nginx max file upload size to 30 MB to match https://github.com/openwisp/openwisp-firmware-upgrader#openwisp-firmware-upgrader-max-file-size.

I think the easiest thing may be to add a way to control `OPENWISP_FIRMWARE_UPGRADER_MAX_FILE_SIZE` with an ansible variable, and use the same variable also to configure the nginx max file upload size.

**Comment by pandafy** [comment]
The values takes by nginx conf and OpenWISP Firmware Upgrader for specifying upload size are different. 

nginx take data values in `10M` notation, while OpenWISP Firmware Upgrader take data value in bytes.

**Comment by nemesisdesign** [comment]
> The values takes by nginx conf and OpenWISP Firmware Upgrader for specifying upload size are different.
> 
> nginx take data values in `10M` notation, while OpenWISP Firmware Upgrader take data value in bytes.

Let's proceed with dividing the value in the jinja2 template or any other equivalent good way of achieving the same.
