### ISSUE TITLE
[change] Rework celery queues to avoid slowing down tasks

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#273]
Recently I changed the configuration of the queues to separate background tasks from monitoring tasks, to avoid having one worker doing everything and stalling because some network task is taking long to finish.

However I realized this is not enough.

Let's immagine a case in which 100 firmware upgrade operations are launched and all the network wokers are executing these upgrades, which may take from 4 minutes to 15 minutes or more each.

This means that for that time, the network worker will be busy doing firmware upgrades, and nor monitoring checks nor any other network operation will be done.

For this reason, I believe we should have 4 different celery workers each one consuming one queue:

- default worker, for application tasks that have to be executed in the background
- monitoring worker: executes active monitoring checks
- firmware upgrader worker: executes firmware upgrade tasks
- network worker: executes config pushes and any other generic network operation

PS: by default we could set the number of processes to be 1 and explain in the README that we do this to ensure the application will run also on small VMs, then we should explain to users that as soon as their instances grow in number of managed devices they will have to increase the number of workers (using concurrency or autoscale) to ensure the tasks in the queues are procesessed in a timely manner.

**Comment by pandafy** [comment]
Closed in #293

**Comment by nemesisdesign** [comment]
Ok to close it (since we closed all the other issues in ow-controller for a similar reason).

The firmware upgrader queue is available in master, the monitoring queue is available in the `dev` branch for now, until it will be released to master.
