### ISSUE TITLE
[docs] Stouts.postfix role mismatch in documentation

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-openwisp2#289]
In documentation, it is suggested to use Stouts.postfix from https://github.com/nemesisdesign/Stouts.postfix

In meta/main.yml, it uses https://github.com/Stouts/Stouts.postfix
https://github.com/openwisp/ansible-openwisp2/blob/0df7136ae8bdd43421b535fd499a012fe408e04f/meta/main.yml#L3-L9

This discrepancy should be resolved and the correct URL should be present at both the places.

**Comment by nemesisdesign** [comment]
Should be fixed now, please double check and let me know.

**Comment by pandafy** [comment]
Thanks! It has been fixed
