### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by imp1sh** [openwisp/ansible-openwisp2#295]
When I install the OpenWisp system via Ansible the nginx systems listens IPv4 only.
As in https://datatracker.ietf.org/doc/html/rfc6540 IPv6 is no longer optional.
Please adjust.

**Comment by nemesisdesign** [comment]
You just need to set one variable to true: https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml#L51.

IPv6 is unfortunately on most systems we deal with and causes issues to novice users trying to install openwisp, some aspects of the default settings of the role are aimed at helping newcomers to get it running.

**Comment by imp1sh** [comment]
I'm not talking about deactivating IPv4 I'm talking about supporting dual stack as a default which won't cause issues for anybody.
