### ISSUE TITLE
[docs] Fix autoscale comments in README and code

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#302]
Our docs and comments regarding [celery autoscaling](https://docs.celeryproject.org/en/stable/userguide/workers.html#autoscaling) is incorrect: we mention that the first value is the min value and the second the max one, but it's the reverse: the max value comes first, the min value after.

We should fix both comments and README, first in `master` branch, then we should rebase on `dev` and fix the autoscaling monitoring value there too.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by pandafy** [comment]
Go ahead @himanshu007-creator! 🚀
