### ISSUE TITLE
[enhancement] Allow users to specify Django version 

### ISSUE THREAD

**Issue by pandafy** [openwisp/ansible-openwisp2#313]
Add a variable to specify which version of Django should be installed. 
This task should be run after everything is installed by pip to avoid accidental upgrades by any other package. 

I think we should default it to `~=3.2.0`, since it is an LTS release of Django (open for discussion).

**Comment by Aryamanz29** [comment]
@pandafy Could you please guide me in which file we have to add a variable for the Django version? ig it's `tasks/pip.yml`?😅

**Comment by pandafy** [comment]
Yes, install Django should be last task in `tasks/pip.yml`.
