### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by deykmora** [openwisp/ansible-openwisp2#329]
buenos días tengo esta falla, así tengo el hosts:

[openwisp2]
192.168.100.115

y asi el playbook

- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    openwisp2_default_from_email: FOSDEM-test

cuando aplico ansible-playbook -i hosts playbook.yml -u debian -k --become -K, me dice:

BECOME password[defaults to SSH password]:

PLAY [openwisp2] ***************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [192.168.100.115]: UNREACHABLE! => {"changed": false, "msg": "Invalid/incorrect password: Permission denied, please try again.", "unreachable": true}

PLAY RECAP *********************************************************************
192.168.100.115            : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

nose como corregirlo ya he echo de todo, estoy en una maquina virtual le instale el debian 11 y llegue hasta este paso, ayuda por favor

**Comment by nemesisdesign** [comment]
This is a bug tracker, if you need help in installing/using OpenWISP please use the [support channels](https://openwisp.org/support.html).
