### ISSUE TITLE
How to create template for globals?

### ISSUE THREAD

**Issue by BlueWaterCrystal** [openwisp/ansible-openwisp2#352]
Hi,

I'm trying to create a template for `config globals 'globals'`, but doesn't change anything on the client.
Would anyone have an example JSON?

**Comment by mikysal78** [comment]
http://netjsonconfig.openwisp.org/en/latest/general/commandline_utility.html

```
netjsonconfig --native your_backup_config.tar.gz --backend openwrt --method json -a indent="    " > pippo
```
vi pippo
