### ISSUE TITLE
Allow an "official" way to install openwisp on a server without an IP address in production

### ISSUE THREAD

**Issue by Lukas-J** [openwisp/ansible-openwisp2#356]
In https://github.com/openwisp/ansible-openwisp2#create-inventory-file you say that `openwisp2.mydomain.com` needs to be a hostname and not an IP address.

In https://github.com/openwisp/ansible-openwisp2#back-to-your-local-machine you then set an IP address for the Virtual Box environment and set the variable `postfix_myhostname` later on.

I think, there should be an "official" way in the Readme for production environments where the infrastructure server don't have a hostname but just an IP address.

PS: Can I use the way in https://github.com/openwisp/ansible-openwisp2#back-to-your-local-machine to set up a server without a hostname or will I face any obstacles?

Cheers!

**Comment by nemesisdesign** [comment]
> I think, there should be an "official" way in the Readme for production environments where the infrastructure server don't have a hostname but just an IP address.

That sound crazy to me. Feel free to edit the ansible role to do that, but that's not something I am going to endorse or recommend. A valid SSL certificate needs a hostname anyway. If you like to do it differently for your own reasons you're free to do it, all the code is open source and open for modification.
