### ISSUE TITLE
openwisp2_radius not installing

### ISSUE THREAD

**Issue by ldt4play** [openwisp/ansible-openwisp2#359]
Installing on clean Debian 10, everything install correct, and get web access, but the radius opcion dont apear. Checking my ansible output, it just dont even tries to install it.
Is something I´m missing? I have tried adding other vars, and they are Installed whitout problem.

My Playbook.yml:

- hosts: myhost
#  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
   openwisp2_network_topology: true
   openwisp2_firmware_upgrader: true
   openwisp2_radius: true
   openwisp2_freeradius_install: true
   openwisp2_radius_urls: true

My  ansible-playbook output:
PLAY [myHost] **********************************************************

TASK [Gathering Facts] *********************************************************
ok: [myHost]

TASK [Stouts.postfix : include_tasks] ******************************************
included: /root/.ansible/roles/Stouts.postfix/tasks/postfix.yml for myHost

TASK [Stouts.postfix : Install requirements (Debian)] **************************
ok: [myHost] => (item=postfix)
ok: [myHost] => (item=ca-certificates)
ok: [myHost] => (item=mailutils)
ok: [myHost] => (item=libsasl2-modules)

TASK [Stouts.postfix : Install DKIM requirements (Debian)] *********************
skipping: [myHost] => (item=opendkim)
skipping: [myHost] => (item=opendkim-tools)

TASK [Stouts.postfix : Install postfix-pcre] ***********************************
skipping: [myHost]

TASK [Stouts.postfix : Install requirements (RedHat)] **************************
skipping: [myHost] => (item=postfix)
skipping: [myHost] => (item=ca-certificates)
skipping: [myHost] => (item=mailx)
skipping: [myHost] => (item=libselinux-python)

TASK [Stouts.postfix : Install DKIM requirements (RedHat)] *********************
skipping: [myHost]

TASK [Stouts.postfix : create self-signed SSL cert] ****************************
skipping: [myHost]

TASK [Stouts.postfix : set permissions for self-signed SSL cert] ***************
skipping: [myHost]

TASK [Stouts.postfix : set permissions for self-signed SSL key] ****************
skipping: [myHost]

TASK [Stouts.postfix : Create DKIM directories] ********************************
skipping: [myHost]

TASK [Stouts.postfix : Create DKIM directories] ********************************
skipping: [myHost] => (item=myHost)

TASK [Stouts.postfix : Generate DKIM key] **************************************
skipping: [myHost] => (item=myHost)

TASK [Stouts.postfix : Change DKIM key permissions] ****************************
skipping: [myHost] => (item=myHost)

TASK [Stouts.postfix : Configure opendkim pt. 1] *******************************
skipping: [myHost]

TASK [Stouts.postfix : Configure opendkim pt. 2] *******************************
skipping: [myHost]

TASK [Stouts.postfix : Configure opendkim pt. 3] *******************************
skipping: [myHost]

TASK [Stouts.postfix : Configure opendkim pt. 4] *******************************
skipping: [myHost]

TASK [Stouts.postfix : Configure opendkim pt. 5] *******************************
skipping: [myHost]

TASK [Stouts.postfix : Ensure /etc/postfix directory is owned by root user] ****
ok: [myHost]

TASK [Stouts.postfix : Configure postfix pt. 1] ********************************
ok: [myHost] => (item=main.cf)
ok: [myHost] => (item=master.cf)

TASK [Stouts.postfix : Configure postfix pt. 2] ********************************
skipping: [myHost]

TASK [Stouts.postfix : Configure postfix pt. 3] ********************************
skipping: [myHost]

TASK [Stouts.postfix : Configure postfix pt. 4] ********************************
ok: [myHost]

TASK [Stouts.postfix : Configure postfix pt. 5] ********************************
skipping: [myHost]

TASK [Stouts.postfix : Configure postfix pt. 6] ********************************
ok: [myHost]

TASK [Stouts.postfix : Configure postfix local user relay] *********************
skipping: [myHost]

TASK [Stouts.postfix : Configure postfix sender canonical maps] ****************
skipping: [myHost]

TASK [Stouts.postfix : Configure SystemD] **************************************
skipping: [myHost]

TASK [Stouts.postfix : Ensure Postfix service is enabled (systemd)] ************
skipping: [myHost]

TASK [Stouts.postfix : Ensure Postfix is started] ******************************
ok: [myHost]

TASK [openwisp.openwisp2 : Set spatialite_path (Ubuntu >= 18.04 or Debian >= 10)] ***
ok: [myHost]

TASK [openwisp.openwisp2 : Update APT package cache] ***************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install system packages] ****************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install redis 6 if available] ***********************
fatal: [myHost]: FAILED! => {"cache_update_time": 1648678530, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'redis-server=5:6*'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n redis-server : Depends: redis-tools (= 5:6.0.15-1~bpo10+1) but 5:5.0.14-1+deb10u2 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " redis-server : Depends: redis-tools (= 5:6.0.15-1~bpo10+1) but 5:5.0.14-1+deb10u2 is to be installed"]}
...ignoring

TASK [openwisp.openwisp2 : Install redis 5 if available] ***********************
ok: [myHost]

TASK [openwisp.openwisp2 : Install redis 4 (fallback)] *************************
skipping: [myHost]

TASK [openwisp.openwisp2 : set redis to listen on ipv4] ************************
ok: [myHost]

TASK [openwisp.openwisp2 : start redis] ****************************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install geographic libraries] ***********************
ok: [myHost]

TASK [openwisp.openwisp2 : Install spatialite] *********************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install mod-spatialite (may fail on older linux distros)] ***
ok: [myHost]

TASK [openwisp.openwisp2 : Install acl if acting as non-root user] *************
skipping: [myHost]

TASK [openwisp.openwisp2 : ensure supervisor is started] ***********************
ok: [myHost]

TASK [openwisp.openwisp2 : Install python3 packages] ***************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install ntp] ****************************************
ok: [myHost]

TASK [openwisp.openwisp2 : Create default SSH key pair] ************************
ok: [myHost]

TASK [openwisp.openwisp2 : Get default private SSH key] ************************
ok: [myHost]

TASK [openwisp.openwisp2 : Get default public SSH key] *************************
ok: [myHost]

TASK [openwisp.openwisp2 : Update pip & related tools] *************************
ok: [myHost]

TASK [openwisp.openwisp2 : Remove jsonfield2] **********************************
ok: [myHost]

TASK [openwisp.openwisp2 : Set openwisp2_python_packages] **********************
ok: [myHost]

TASK [openwisp.openwisp2 : Set custom package list] ****************************
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)
skipping: [myHost] => (item=False)

TASK [openwisp.openwisp2 : Add network_topology to custom package list if set and enabled] ***
skipping: [myHost] => (item=False)

TASK [openwisp.openwisp2 : Add firmware_upgrader to custom package list if set and enabled] ***
skipping: [myHost] => (item=False)

TASK [openwisp.openwisp2 : Install openwisp2 controller and its dependencies] ***
changed: [myHost]

TASK [openwisp.openwisp2 : Pin channels_redis to 2.4 for redis 4 compatibility] ***
changed: [myHost]

TASK [openwisp.openwisp2 : Install django-redis] *******************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install openwisp2 network topology and its dependencies] ***
skipping: [myHost]

TASK [openwisp.openwisp2 : Install openwisp firmware upgrader and its dependencies] ***
skipping: [myHost]

TASK [openwisp.openwisp2 : Install extra python packages] **********************
ok: [myHost]

TASK [openwisp.openwisp2 : Install custom OpenWISP 2 Python packages] **********
skipping: [myHost]

TASK [openwisp.openwisp2 : Install static minification dependencies] ***********
ok: [myHost]

TASK [openwisp.openwisp2 : Install uwsgi] **************************************
ok: [myHost]

TASK [openwisp.openwisp2 : Install psycopg2] ***********************************
skipping: [myHost]

TASK [openwisp.openwisp2 : Install MySQL-python] *******************************
skipping: [myHost]

TASK [openwisp.openwisp2 : Install raven (sentry client)] **********************
skipping: [myHost]

TASK [openwisp.openwisp2 : create /opt/openwisp2] ******************************
ok: [myHost]

TASK [openwisp.openwisp2 : create "/opt/openwisp2/openwisp2"] ******************
ok: [myHost]

TASK [openwisp.openwisp2 : create "/opt/openwisp2/log"] ************************
ok: [myHost]

TASK [openwisp.openwisp2 : manage.py] ******************************************
ok: [myHost]

TASK [openwisp.openwisp2 : celery.py] ******************************************
ok: [myHost]

TASK [openwisp.openwisp2 : __init__.py] ****************************************
ok: [myHost]

TASK [openwisp.openwisp2 : urls.py] ********************************************
changed: [myHost]

TASK [openwisp.openwisp2 : wsgi.py] ********************************************
ok: [myHost]

TASK [openwisp.openwisp2 : asgi.py] ********************************************
ok: [myHost]

TASK [openwisp.openwisp2 : upload generate_django_secret_key.py script] ********
ok: [myHost]

TASK [openwisp.openwisp2 : generate new django SECRET_KEY] *********************
ok: [myHost]

TASK [openwisp.openwisp2 : get django SECRET_KEY] ******************************
ok: [myHost]

TASK [openwisp.openwisp2 : set permission to secret key file] ******************
ok: [myHost]

TASK [openwisp.openwisp2 : set secret_key fact] ********************************
ok: [myHost]

TASK [openwisp.openwisp2 : settings.py] ****************************************
changed: [myHost]

TASK [openwisp.openwisp2 : storage.py] *****************************************
ok: [myHost]

TASK [openwisp.openwisp2 : routing.py] *****************************************
ok: [myHost]

TASK [openwisp.openwisp2 : migrate] ********************************************
[WARNING]: Unable to use /var/www/.ansible/tmp as temporary directory, failing
back to system: [Errno 13] Permission denied: '/var/www/.ansible'
ok: [myHost]

TASK [openwisp.openwisp2 : set permissions to sqlite db] ***********************
skipping: [myHost]

TASK [openwisp.openwisp2 : set permissions to "/opt/openwisp2/static"] *********
ok: [myHost]

TASK [openwisp.openwisp2 : collectstatic] **************************************
ok: [myHost]

TASK [openwisp.openwisp2 : create load_initial_data.py script] *****************
ok: [myHost]

TASK [openwisp.openwisp2 : load initial data] **********************************
ok: [myHost]

TASK [openwisp.openwisp2 : uwsgi.ini] ******************************************
ok: [myHost]

TASK [openwisp.openwisp2 : supervisor uwsgi] ***********************************
ok: [myHost]

TASK [openwisp.openwisp2 : supervisor daphne] **********************************
ok: [myHost]

TASK [openwisp.openwisp2 : supervisor celery] **********************************
ok: [myHost]

TASK [openwisp.openwisp2 : supervisor celery network] **************************
ok: [myHost]

TASK [openwisp.openwisp2 : supervisor celery firmware_upgrader] ****************
skipping: [myHost]

TASK [openwisp.openwisp2 : supervisor celerybeat] ******************************
ok: [myHost]

TASK [openwisp.openwisp2 : Remove supervisor runworker.conf (obsolete)] ********
ok: [myHost]

TASK [openwisp.openwisp2 : create "/opt/openwisp2/public_html"] ****************
ok: [myHost]

TASK [openwisp.openwisp2 : create "/opt/openwisp2/ssl"] ************************
ok: [myHost]

TASK [openwisp.openwisp2 : create SSL cert if not exists yet] ******************
ok: [myHost]

TASK [openwisp.openwisp2 : disable default nginx configuration] ****************
ok: [myHost]

TASK [openwisp.openwisp2 : nginx site available] *******************************
ok: [myHost]

TASK [openwisp.openwisp2 : nginx site enabled] *********************************
ok: [myHost]

TASK [openwisp.openwisp2 : configure nginx log rotation] ***********************
ok: [myHost]

TASK [openwisp.openwisp2 : Install topology update cron] ***********************
skipping: [myHost]

TASK [openwisp.openwisp2 : Install topology snapshot save cron] ****************
skipping: [myHost]

TASK [openwisp.openwisp2 : Install clearsessions cronjob] **********************
ok: [myHost]

TASK [openwisp.openwisp2 : Change superuser password hint] *********************
skipping: [myHost]

TASK [openwisp.openwisp2 : Update site object hint] ****************************
skipping: [myHost]

RUNNING HANDLER [openwisp.openwisp2 : reload supervisor] ***********************
changed: [myHost]

PLAY RECAP *********************************************************************
myHost             : ok=71   changed=5    unreachable=0    failed=0    skipped=40   rescued=0    ignored=1

**Comment by vkhalil** [comment]
Hi,

Same here.
