### ISSUE TITLE
Automatically configure DEFAULT_FROM_EMAIL

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#37]
Avoid email being sent as "webmaster@localhost".

The setting should have a good default value but also be customizable.

**Comment by R9295** [comment]
What could be a good default value? "admin@examle.com"?

**Comment by nemesisdesign** [comment]
something like `openwisp2@{{ inventory_hostname }}`, but I don't know what would happen in case `{{ inventory_hostname }}` would be an ip address.

We should add this new variable to the list of available variables but I think we should also highly suggest to set it manually in the playbook by updating our examples in the README to mention this.

Why we need to do this? Because as soon as people start using openwisp2 in a production environment, the system will try to send emails when new users are created or a password is reset, but if not configured correctly either the email won't be sent or the system may crash entirely so we gradually have to fix each case until we have good defaults that work in most cases without too much user intervention.

**Comment by R9295** [comment]
What could be a good way to explain it in the README? I'm thinking something along these lines:
"It is recommend that you change the value of this variable if you intend to use OpenWISP2 in production, as a misconfiguration  may result in emails not being sent "

**Comment by nemesisdesign** [comment]
Yes that's fine, I think I also replied via chat so you should be ready to go, we'll improve during the review also so don't worry.
