### ISSUE TITLE
Bump openwisp2_controller_version to 1.0.0

### ISSUE THREAD

**Issue by eric-j-ason** [openwisp/ansible-openwisp2#372]
In the [latest release](https://github.com/openwisp/ansible-openwisp2/blob/a0027d2751cf9dcd26bef846d3c822040e0c483e/defaults/main.yml#L7) of ansible-openwisp2 (0.15.0), as well as in the current [`master`](https://github.com/openwisp/ansible-openwisp2/blob/7b37a0b07b8ff5c98367ec3432ef05bf4bf59969/defaults/main.yml#L11), `openwisp2_controller_version` is set to `0.8.2`. Since then, versions 0.8.3, 0.8.4, and, recently, 1.0.0 of openwisp-controller has come out.

It would be great to update to this latest version of openwisp-controller, and release a new version of ansible-openwisp2 on [Ansible Galaxy](https://galaxy.ansible.com/openwisp/openwisp2), so that it becomes available to users.

**Comment by eric-j-ason** [comment]
@nemesisdesign: Thanks! Is there an issue, a milestone, or similar, where the remaining steps are tracked?

**Comment by nemesisdesign** [comment]
> Edit: Is [this](https://github.com/openwisp/ansible-openwisp2/milestone/1) the right place to look?

Yes, even better is to join the [support chat](https://gitter.im/openwisp/general), the [mailing list](https://groups.google.com/d/forum/openwisp/join), or [twitter](https://twitter.com/openwisp) to receive announcements of new releases.
