### ISSUE TITLE
802.1q and bridge vlan filtring

### ISSUE THREAD

**Issue by nikolya-prodigy** [openwisp/ansible-openwisp2#385]
Hello.
I use MT7621 CPU routers that don't have a separate switch.
Nevertheless, in the openwrt settings, I can create an 802.1q interface or work with vlan via bridge vlan filtring, but I did not find such functionality in openwisp.
The programmable switch is not suitable for me, since this setting is for routers that have a separate HW switch.
Is there any way to implement this support?

config bridge-vlan
        option device 'br0'
        option vlan '1'
        list ports 'lan1'
        list ports 'lan2'
        list ports 'lan3'
        list ports 'wan'

config bridge-vlan
        option device 'br0'
        option vlan '10'
        list ports 'lan4:u*'
        list ports 'wan:t'

Here bridge and management are in vlan 1 and port 4 of vlan 10

and 802.1q

config device
        option type '8021q'
        option ifname 'br0'
        option vid '10'
        option name 'eth0.10'

**Comment by nemesisdesign** [comment]
This is being tracked in https://github.com/openwisp/netjsonconfig/issues/195.
