### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#39]
Invalid

**Comment by R9295** [comment]
Yeah I'll take a look at it

**Comment by R9295** [comment]
@nemesisdesign yeah, your proposed solution works

**Comment by xamfy** [comment]
@R9295 are you still working on this?

**Comment by R9295** [comment]
@xamfy  this is gonna be GCI task.

**Comment by xamfy** [comment]
@R9295 oh, I see
