### ISSUE TITLE
[uwsgi] Add uid option

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#40]
Add `uid=www-data`, ensuring dirs on which uwsgi has to write are writable.

**Comment by xamfy** [comment]
Can I try?

**Comment by nemesisdesign** [comment]
@xamfy sure, would be a good way to warm up with ansible.

This is the file: https://github.com/openwisp/ansible-openwisp2/blob/master/templates/uwsgi.ini.j2
The problem is that permissions must be set correctly, probably www-data must own the dir in which the process writes, most likely openwisp2_path and openwisp2_path/log, but I'm going from memory.

Ensure to test the change before sending the pull request!

**Comment by xamfy** [comment]
Please close this issue, I addressed the wrong one in my PR.

**Comment by nemesisdesign** [comment]
AHAH lol
