### ISSUE TITLE
Unable to complete deployment from ansible

### ISSUE THREAD

**Issue by tdoucet-ecotel** [openwisp/ansible-openwisp2#422]
Ansible 2.10.8 on Ubuntu Server 22.04.1
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/125287381/218495200-b0ad1c22-c577-48a2-8c7f-b7f505ec57ca.png)

**Comment by nemesisdesign** [comment]
@tdoucet-ecotel please post the error in the form of text instead of screenshots, please reopen the issue once that is done.

**Comment by doucettom** [comment]
fatal: [1001lab-openwisp-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "insertafter": "  # index-version = \"inmem\"",
            "line": "  index-version = \"inmem\"",
            "path": "/etc/influxdb/influxdb.conf",
            "search_string": "  index-version ="
        }
    },
    "msg": "Unsupported parameters for (lineinfile) module: search_string Supported parameters include: attributes, backrefs, backup, create, firstmatch, group, insertafter, insertbefore, line, mode, owner, path, regexp, selevel, serole, setype, seuser, state, unsafe_writes, validate"
}
