### ISSUE TITLE
does not work on vanilla ubunu 20.04

### ISSUE THREAD

**Issue by xewonder** [openwisp/ansible-openwisp2#423]
hello

all your steps just do not work .. 

wasted too many hours on this

I can give you  vanilla ubuntu 20.04 for you so that you can "correct" your instructions??

don't aks me for errors, as they differ EVERY TIME!

**Comment by nemesisdesign** [comment]
Please reopen the issue copy/pasting the error you're getting (when the moderation time I have set on the organization expires).
I would also recommend to try on Ubuntu 22.04. BTW, all builds are running fine now, there may be occasional issues but throwing tantrums like this is not cool.
