### ISSUE TITLE
does not work on vanilla ubunu 22.04

### ISSUE THREAD

**Issue by xewonder** [openwisp/ansible-openwisp2#424]
Good day,

Referring to  #423

...from my 36 previous hours trying  to install on 20.04, the errors differ...  

following all instructions (apart from pip and ansible install - that do not work from instructions and have to be installed manually) it also does not work on vanilla Ubuntu 22.04.

`TASK [openwisp.openwisp2 : create SSL cert if not exists yet] ********************************************************************************************************************************************************************
fatal: [xxx.xxx.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _raw_params, _uses_shell, argv, chdir, creates, executable, removes, stdin, stdin_add_newline, strip_empty_ends."}`

install stops.

>>>>>>>>
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

>>>>>>>>>

**Comment by nemesisdesign** [comment]
This should have been solved by this commit: https://github.com/openwisp/ansible-openwisp2/commit/d73f819021ff78a55806edd3d7cebdd4f691b348
Try using the latest dev version.
