### ISSUE TITLE
Installing openwisp2 on localhost using kali: fatal: [localhost]: FAILED! => {" changed": false, "msg": "Failed, to update apt cache: E: The repository 'https://repos.influxdata.com/kali kali-rolling Release' does not have a Release file."'}

### ISSUE THREAD

**Issue by gh0str1ddler** [openwisp/ansible-openwisp2#435]
I had this error when install openwisp2. I followed every step. Ansible is installed and up to date. Python is latest version (3.11). I've attached my playbook file and hosts file. I'm trying to install it locally on kali. 
I went to the repos indicated in the error and found out it doesn't exist and the only supported releases are debian and ubuntu and since kali is a debian linux OS, is there any way to make this update through a debian repo or anything else in order to make opebwisp work????
[hosts and playbook.zip](
[error.txt](https://github.com/openwisp/ansible-openwisp2/files/11409529/error.txt)
https://github.com/openwisp/ansible-openwisp2/files/11409475/hosts.and.playbook.zip)

**Comment by kasraghu** [comment]
Instructions to install deb package are [here](https://repos.influxdata.com/debian/dists/)

You can skip the installation of Influxdb by setting `openwisp2_influxdb_install: true` [role variable](https://github.com/openwisp/ansible-openwisp2#role-variables)

**Comment by nemesisdesign** [comment]
Your error is showing that influxdb can't find the following package source:
```
https://repos.influxdata.com/kali kali-rolling Release
```
Are you trying to install on kali linux?
That distro is not supported. Only Ubuntu and Debian targets.
