### ISSUE TITLE
authorize the NAS from Openwisp DB

### ISSUE THREAD

**Issue by Forrest-It** [openwisp/ansible-openwisp2#455]
I would like to authorize the NAS by reading from the Openwisp DB: I tried to enable the sql module, in this way
dialect = "sqlite"  
sqlite {
                filename = "/opt/openwisp2/db.sqlite3"
....
 driver = "rlm_sql_sqlite"
 read_clients = yes
 client_table = "nas"

i don't undestand why i have this error : 0) 
rest: ERROR: Server returned:
(0) rest: ERROR: {"detail":"JSON parse error - Invalid \\escape: line 1 column 4                                         0 (char 39)"}

I noticed that as soon as I enable the sql module, the password is no longer clear in the freeradius -X debug

can someone help me understand 

Thank you

Tommaso

**Comment by nemesifier** [comment]
Please use the mailing list and or support chat for questions. We use github only to report bugs.
