### ISSUE TITLE
[change] Update "delete_old_users" to "delete_old_radiusbatch_users"

### ISSUE THREAD

**Issue by praptisharma28** [openwisp/ansible-openwisp2#463]
**Current Behavior:**
The `delete_old_users` command within the OpenWISP project is responsible for deleting users created using RadiusBatch. However, the current name might be misleading as it implies a broader functionality than it actually has.

**Proposed Change:**
This PR addresses the changes made in response to Issue https://github.com/openwisp/openwisp-radius/issues/496. The issue was successfully resolved, leading to a modification in the command name from delete_old_users to delete_old_radiusbatch_users for improved clarity and functionality.

As part of this update, related traces in this repository were identified. These issues are being addressed in parallel to this PR to maintain coherence within the codebase.

**Documentation Update:**
The documentation will be updated accordingly to reflect the new command name, ensuring that users can easily understand and use it as intended.

**Related Issues:**
This PR addresses concerns raised in https://github.com/openwisp/openwisp-radius/issues/496 and https://github.com/openwisp/docker-openwisp/issues/294.

**Code Traces:**
To maintain backward compatibility and ensure a smooth transition, the PR will update variable names as necessary. Specifically, changes will be made in the `settings.py` file within the `ansible-openwisp2` repository, as highlighted in https://github.com/openwisp/ansible-openwisp2/blob/ce426d33759db9e3d9ea5048521c226676473d88/templates/openwisp2/settings.py#L280-L285.

**Comment by praptisharma28** [comment]
@nemesifier

**Comment by pandafy** [comment]
Thanks for opening and updating the issue @praptisharma28! 👏🏼
