### ISSUE TITLE
[change] Support Debian 12

### ISSUE THREAD

**Issue by abplayzGH** [openwisp/ansible-openwisp2#473]
When trying to install on a privileged lxc container with Debian 12, the playbook returns an error when setting  "Set the index-version for influxdb". 

`
TASK [openwisp.influxdb : Set the index-version for influxdb] ****************************************************************************************
fatal: [openwisp.impostertwo.us]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (lineinfile) module: search_string Supported parameters include: attributes, backrefs, backup, content, create, delimiter, directory_mode, firstmatch, follow, force, group, insertafter, insertbefore, line, mode, owner, path, regexp, remote_src, selevel, serole, setype, seuser, src, state, unsafe_writes, validate"}
`

**Comment by abplayzGH** [comment]
Debian 12 not supported.

**Comment by nemesifier** [comment]
@abplayzGH correct, not supported yet, but we will have to do this, I think you're not the first one reporting this, probably others have reported this in the general chat or in the mailing list. Let me reopen the issue and change the title.
