### ISSUE TITLE
Add support for Fedora / RedHat / Centos

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#5]
Fedora is a popular linux distribution that is suitable to be used for hosting an openwisp2 instance.

The parts to change to add support to Fedora are the following ones:

- management of system packages: use yum module instead of apt and the names of some packages are different
- nginx configuration, path differ slightly
- supervisord configuration, a few things differ here too

**Comment by moonwolf-github** [comment]
And CentOS7/RHEL7 support is also missing.

**Comment by moonwolf-github** [comment]
I think i did it. It's not yet flawlessly nor pretty (it's my first contact with ansible and yaml) but looks like it works...

**Comment by nemesisdesign** [comment]
@moonwolf-github show me something and I'll try to help you out

**Comment by moonwolf-github** [comment]
I've forked your repo and my work is here: https://github.com/moonwolf-github/ansible-openwisp2/tree/centos_support. AFAIR there were two main problems: during virtualenv creation one python file was missing, and i had to turn off SELinux because of Django app path (/opt/). i didn't want to mess around with file locations. Both issues are somehow fixable of course.
I'll verify this out tomorrow and report back.

**Comment by nemesisdesign** [comment]
Hi @moonwolf-github, thank you for this update.

**Comment by moonwolf-github** [comment]
As i said there is a problem with virtualenv creation:
`{"cmd": "/usr/bin/virtualenv --system-site-packages -ppython3 /opt/openwisp2/env", "failed": true, "item": "pip", "msg": "stdout: Using base prefix '/usr'\nNew python executable in /opt/openwisp2/env/bin/python3\nAlso creating executable in /opt/openwisp2/env/bin/python\nERROR: The executable /opt/openwisp2/env/bin/python3 is not functioning\nERROR: It thinks sys.prefix is '/tmp' (should be '/opt/openwisp2/env')\nERROR: virtualenv is not compatible with this system or executable\nRunning virtualenv with interpreter /usr/bin/python3\n\n:stderr: Failed to import the site module\nTraceback (most recent call last):\n  File \"/opt/openwisp2/env/lib64/python3.4/site.py\", line 67, in <module>\n    import os\n  File \"/opt/openwisp2/env/lib64/python3.4/os.py\", line 618, in <module>\n    from _collections_abc import MutableMapping\nImportError: No module named '_collections_abc'\n"}`

It may be bug in CentOS7's version of virtualenv as described [here](https://github.com/pypa/virtualenv/issues/463). [Here](http://stackoverflow.com/a/23842752/2643014) is suggestion to upgrade virtualenv with pip. I'm not sure it's a good idea, maybe i should copy/link this file (`_collections_abc.py`) with ansible as this resolves this issue?

Or use python 3.5 from SCL - but this is more complicated as it is installed beside system python and needs to be enabled before use (i don't know how yet).

Apart this i had to disable SELinux and firewall - these issues also need to be addressed as they are big security holes. But first i need to learn ansible little more.

**Comment by nemesisdesign** [comment]
I think upgrading virtualenv could be an acceptable solution.

Yes, let's keep the system python as you suggested, installing a different python version may lead to unexpected issues.

If you want to learn ansible, I suggest you "Ansible for DevOps", is a short good book I've read that gives you an excellent overview.

**Comment by Germano0** [comment]
I attach a translation of packages names from Debian to Fedora
```

DEBIAN PACKAGE NAME | FEDORA PACKAGE NAME

python-software-properties | It is not necessary (According to http://superuser.com/questions/991089/yum-install-software-properties-common-on-ec2 )
build-essential | make automake gcc gcc-c++ kernel-devel
libssl-dev | openssl-devel
libffi-dev | libffi-devel
nginx
openssl | openssl
python-dev | python-devel
python-pip | python-pip
python-dev | python-devel
python3 | python3
python3-pip | python3-pip
python-wheel | python2-wheel
python3-wheel | python3-wheel
python-virtualenv | N/A
sqlite3 | sqlite
supervisor | supervisor
```

**Comment by nemesisdesign** [comment]
Also supervisord conf files should be stored in a slightly different dir

**Comment by nemesisdesign** [comment]
Done. Thank you all @moonwolf-github @Germano0 @evgeni
