### ISSUE TITLE
[docs] Local installation for testing

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#51]
I think it would be better to replace the section named "Install OpenWISP2 locally (laptop, desktop pc)" with a section that explains how to install OpenWISP 2 in a virtualbox VM, the same task we have asked GCI students to perform and for which they encountered all the same issues.

We can use their experience to prepare a step by step tutorial for this case that would probably work better than the kind of suggestion we give now.

**Comment by nemesisdesign** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by UtkarshVerma** [comment]
Did it. Here's the link to the PR: https://github.com/openwisp/ansible-openwisp2/pull/70

**Comment by UtkarshVerma** [comment]
#70
