### ISSUE TITLE
[python3] Drop supports for platforms that do not offer python 3.5 by default

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#61]
Django 2.0 officially suggests to use python 3.5 or higher.

OpenWISP will soon be python 3 only.

**Comment by nemesisdesign** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by ankitkataria** [comment]
@nemesisdesign i have been reading about ansible roles, can i take up this issue?

**Comment by nemesisdesign** [comment]
@ankitkataria sure!
Remember to perform this task only if [openwisp2_python](https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml#L1) variable contains the string `python3`.
 eg: `when: 'python3' in openwisp2_python`

**Comment by ankitkataria** [comment]
@nemesisdesign https://www.python.org/ftp/python/ this url has all the python versions, they can be simply installed on any linux distribution. is it even necessary to check if an update to python3.5 or 3.6 is available in the packages? Why not simply download and install 3.6 from the above link is openwisp2_python is set to python3?

**Comment by nemesisdesign** [comment]
@ankitkataria how would you install it? Does it have to be compiled? Not sure it would work well (without introducing other issues) but we can try.
If it needs to be compiled I want us to use [checkinstall](https://debian-administration.org/article/147/Installing_packages_from_source_code_with_checkinstall) which gives the possibility of uninstalling the package if needed.

We should not do this by default though. Initially we can make it optional and encourage people to try (I'd use it as well on a few instances), then after a few months if everything goes well it can become the default.

**Comment by ankitkataria** [comment]
@nemesisdesign thankyou for having a look at my PRs :smile: I'm a little busy with my exams right now and make a new PR as soon as they are over. Thanks again.

**Comment by nemesisdesign** [comment]
@atb00ker is python3 available on Fedora / EL/ Centos?

**Comment by atb00ker** [comment]
`debian8` doesn't have required python3 version available & the community has closed that issue as `wontfix`.
`centos7` doesn't have python3 installed by default, it can be installed but the process is not through `yum`, rather 3rd party solution so possibly some organization's policies might not allow it.
All `fedora >=26` support python3. :smile:

**Comment by nemesisdesign** [comment]
So in order to migrate to python 3.5 by default we have to remove support for debian8, centos7 and any fedora that is lower than 26, right? We could use this issue to track this change.
I don't think it's a good idea to try installing python 3.5 / 3.6 via ansible.

**Comment by atb00ker** [comment]
@nemesisdesign 

No, No, correction! 
I mentioned the distros that have python3 available through default package manager and default sources list.

I'll check the distros with python3 as default python version and get back here, asap! :smile:

**Comment by nemesisdesign** [comment]
@atb00ker thanks a lot for your research!

PS: on the django mailing list there's a discussion about dropping support for python 3.5 in django 3.0, it seems django 3.0 may be only >= python 3.6.

Stuff is moving quite fast nowadays!

**Comment by nemesisdesign** [comment]
I think this can be closed because we now support only recent distros.
