### ISSUE TITLE
[django] Add support for CORS (Cross-Origin Resource Sharing)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#69]
We need to make it possible to enable CORS because [other applications may need to access some APIs to get data](https://lists.funkfeuer.at/pipermail/interop-dev/2017-December/000732.html).

We can use this module: [django-cors-headers](https://pypi.python.org/pypi/django-cors-headers/2.1.0) - which is configurable via django settings, we have to make sure we can configure every available setting of this module, possibly using a single ansible variable containing a dictionary.
  
This feature should be optional and turned off by default now.

**Comment by UtkarshVerma** [comment]
Would a prompt at playbook runtime be better for configuring CORS? Or should I just create a global modifiable ansible dictionary variable?

**Comment by nemesisdesign** [comment]
let's keep it simple now, a dictionary is cool. I think @R9295 is working on this, are you Aarnav?

**Comment by UtkarshVerma** [comment]
Ok, got it.

**Comment by R9295** [comment]
Yes, I am.

**Comment by b-thebest** [comment]
Can I work on this

**Comment by Sanditya2510** [comment]
Hi @nemesisdesign is this still open?

**Comment by pandafy** [comment]
@Sanditya2510 this issue is still relevant. You can go ahead and work on this if you want to.

**Comment by Sanditya2510** [comment]
> @Sanditya2510 this issue is still relevant. You can go ahead and work on this if you want to.

Ok great, I will setup the application and start working on this issue.
Thanks

**Comment by Aryamanz29** [comment]
I'm working on this
