### ISSUE TITLE
Ansible install does not work

### ISSUE THREAD

**Issue by saurabhchakrabarti** [openwisp/ansible-openwisp2#71]
I've started evaluating this project once again after a long break. I'm getting the following error when I try to deploy using ansible

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/etc/ansible/roles/openwisp.openwisp2/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

## tasks
- import_tasks: variables.yml
  ^ here


The error appears to have been in '/etc/ansible/roles/openwisp.openwisp2/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

## tasks
- import_tasks: variables.yml
  ^ here

```

Things work when I replace import_tasks with include. 

ansible version - 2.3.1.0
Ubuntu 16.04.2 LTS

**Comment by UtkarshVerma** [comment]
Seems to be a bug with with your ansible version.  Try installing the latest version and then there shouldn't be any issue.

**Comment by saurabhchakrabarti** [comment]
Which version are you using?

**Comment by UtkarshVerma** [comment]
v2.4.2.0 . Install it by referring to the docs [here](http://docs.ansible.com/ansible/latest/intro_installation.html)

**Comment by saurabhchakrabarti** [comment]
I'll need to verify this. If that's the problem,  the documentation needs to be changed, since the ansible minimum version mentioned is 2.2

**Comment by UtkarshVerma** [comment]
Yeah, great point. Originally the repo files had the keyword `include` but due to deprecation messages, they have been updated to `import_tasks` leaving the minimum ansible requirement behind. It's clearly stated [here](https://docs.ansible.com/ansible/2.4/import_tasks_module.html) that `import_tasks` is a new keyword in ansible 2.4

**Comment by UtkarshVerma** [comment]
Edit the readme and create the pull request

**Comment by nemesisdesign** [comment]
@UtkarshVerma thx for helping out! :+1:
