### ISSUE TITLE
Issues with Host-only Adapter

### ISSUE THREAD

**Issue by UtkarshVerma** [openwisp/ansible-openwisp2#74]
The host only-adapter is causing issues with internet connectivity on my VM and hence ansible can't download packages.

This issue is regarding the VM installation instructions.

**Comment by nemesisdesign** [comment]
Can you try this?

https://askubuntu.com/questions/293816/in-virtualbox-how-do-i-set-up-host-only-virtual-machines-that-can-access-the-in
