### ISSUE TITLE
Missing headers when instaling on arbian based on debian strech

### ISSUE THREAD

**Issue by Yasen6275** [openwisp/ansible-openwisp2#81]
Tried to install controller on SBC with armbian based on Debian Strech and got veeery long error.

The major clue in it was: 
"   The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source."
After installing libjpeg-dev, instalation went smoothly

**Comment by nemesisdesign** [comment]
@Yasen6275 Thanks for reporting, are you talking about "Armbian"?
