### ISSUE TITLE
[django] Internal server error / permission denied

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#85]
I've noticed a periodic internal server error on some instances.

At first sight it seems that some processes crash and exit because they can't write to logs for permission reasons. It seems the permission of some logs change from `www-data` to `root` at some point. Further investigation is needed.

**Comment by atb00ker** [comment]
I think it's because of that redis-server not starting problem. (which has been fixed)
Since we have added a [subset of tests](https://github.com/openwisp/ansible-openwisp2/blob/master/tests/runtests.sh) to the to avoid it. Is there anything else that we can do here? :smile: 
Thanks.

**Comment by nemesisdesign** [comment]
This problem has been showing up more and more lately, I'm not sure how to fix it.

It seems that some operations change the ownership of log files or static files to the root user, or other files, and then www-data cannot write to these files anymore.

A possible solution could be to create a dedicated linux group, add both www-data, root and any user running the playbook to it, then change the group ownership of all the files to be on this new group, as well as set this group as the default group for all the directories in the installation dir of openwisp.

**Comment by nemesisdesign** [comment]
I found out that the daphne process was not being run as www-data but as root, which caused some of the logs to change ownership after application restart. I fixed this in 17a9099.
I think the definitive fix would include forcing the contents in `logs/` and `static/` to be owned by www-data (user and group) and have write permission both to user and group by default.

**Comment by nemesisdesign** [comment]
After https://github.com/openwisp/ansible-openwisp2/commit/17a9099b895d4fc90314737cf341cd776f58c01a I have not noticed this problem anymore, so I think it's ok to close this issue now, I will reopen if I encounter it again.
