### ISSUE TITLE
[qa] Add ansible linter to build

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#91]
Galaxy [complains a lot during import time](https://galaxy.ansible.com/my-imports?repository_name=openwisp2&selected=282340&page_size=10).

It's probably time to introduce some automated quality checking tool which will help to keep the ansible code up to date with current best practices.

A possible solution would be to use this linter:

- https://github.com/willthames/ansible-lint

**Comment by hispanico** [comment]
I've found info about the lint in ansible galaxy:
https://robertdebock.nl/blog.html
https://github.com/ansible/galaxy-lint-rules

**Comment by nemesisdesign** [comment]
@hispanico great! Did we already publish a GCI task for this?

**Comment by hispanico** [comment]
I think so, there is one tasks about ansoble-lint
