### ISSUE TITLE
[docs] Include documentation for developer setup

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#92]
Setup process for development is not mentioned in README
The process is as follows:
1. [Create playbook.yml](https://github.com/openwisp/ansible-openwisp2#create-playbook-file)
2. Create a directory `roles/`
3. Inside `roles/`, clone `ansible-openwisp2` and [`Shouts.postfix`](https://github.com/nemesisdesign/Stouts.postfix):
```
git clone https://github.com/openwisp/ansible-openwisp2.git openwisp.openwisp2
git clone https://github.com/nemesisdesign/Stouts.postfix.git
```
4. [Run the playbook](https://github.com/openwisp/ansible-openwisp2#run-the-playbook)

**Comment by nemesisdesign** [comment]
I use a different approach, I link the github repos to `~/.ansible/roles`. Some research should be done if there's a standard way to do this.

**Comment by atb00ker** [comment]
I found the method i used from [ansible docs](https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html#using-roles).
It doesn't mention any standard about the folder before `roles/`.

**Comment by nemesisdesign** [comment]
At least we should make sure that when cloning `ansible-openwisp2`, we give it the same name it has on galaxy, eg:

```
git clone https://github.com/openwisp/ansible-openwisp2.git
```

This way we can have:

```
 roles:
    - openwisp.openwisp2
```

Which is identical to what's already documented and hence simpler to maintain, explain and support.
