### ISSUE TITLE
[bug] Server Error (500) on Fedora Systems

### ISSUE THREAD

**Issue by atb00ker** [openwisp/ansible-openwisp2#94]
On fedora systems after installation, Server Error (500) is received when admin tries to login.

**Steps to reproduce**: 
1. Run anisble-openwisp2
2. After completion open browser and login with username & password `admin` on `/admin`.

**Comment by atb00ker** [comment]
**Reason**:
`redis-server` is not running. Hence `Error 111 connecting to localhost:6379` is causing the server error.

**Temporary workaround (for while a patch is made)**: 
Run the following command on the server:
```
redis-server --daemonize yes
```

**Comment by imp1sh** [comment]
CentOS 7 also suffers from this bug. The workaround works though.
