### ISSUE TITLE
Remove automatic organization creation in favour of data migration

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#95]
Some lines in [load_initial_data.py](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/load_initial_data.py#L24-L38) can be removed once both of the following issues are resolved and both packages have been released on pypi:

- https://github.com/openwisp/openwisp-users/issues/29
- https://github.com/openwisp/openwisp-controller/issues/39

**Comment by ankit-kumar-dwivedi** [comment]
> Some lines in [load_initial_data.py](https://github.com/openwisp/ansible-openwisp2/blob/master/templates/load_initial_data.py#L24-L38) can be removed once both of the following issues are resolved and both packages have been released on pypi:
> 
>     * [openwisp/openwisp-users#29](https://github.com/openwisp/openwisp-users/issues/29)
> 
>     * [openwisp/openwisp-controller#39](https://github.com/openwisp/openwisp-controller/issues/39)


@nemesisdesign I see the both issues mentioned are resolved can this be assign me this one? :smile:

**Comment by ankit-kumar-dwivedi** [comment]
> @ankit-kumar-dwivedi yes you can work on it, although we won't be able to merge until `openwisp-controller` has been released to pypi

Okay @nemesisdesig this can be start for me getting familiar with codebase, will look for slightly difficult issue next time
