### ISSUE TITLE
please find problem in my playbook,yml for older version of openwisp controller as 0.2.3

### ISSUE THREAD

**Issue by bankimr** [openwisp/ansible-openwisp2#98]
- hosts: openwisp2
  become: "{{ become | default('yes') }}"
  roles:
    - openwisp.openwisp2
  vars:
    postfix_myhostname: "strix-Sun-Fire-X4100-Server"
    openwisp2_network_topology: true
    openwisp2_controller_pip: openwisp-controller==0.2.3
    openwisp2_python: python2.7
    openwisp2_default_from_email: "******"

**Comment by nemesisdesign** [comment]
Please read here: http://openwisp.org/support.html
I suggest to send an email to the list explaining in detail what happened and posting your configuration.
We need more context to help you. But please don't use the bug tracker for problems that are not bugs.
