### ISSUE TITLE
Fails on Debian 10

### ISSUE THREAD

**Issue by hispanico** [openwisp/ansible-openwisp2#99]
Task "[openwisp.openwisp2 : migrate]" fails on Debian 10:
https://gitlab.com/openwisp/ansible-openwisp2/-/jobs/102246224

**Comment by nemesisdesign** [comment]
@hispanico don't forget to add this kind of issues to the contributor's board by selecting the board from `Projects` in the right column here >>>

**Comment by nemesisdesign** [comment]
Does it still fail? If yes @hispanico can you create a GCI task for this please? And If not close please?
PS: if you manage to create the GCI task, add me and @atb00ker as mentors as well please.

**Comment by hispanico** [comment]
In the latest pipeline the build for Debian10 succeeded.
https://gitlab.com/openwisp/ansible-openwisp2/-/jobs/113424380

**Comment by atb00ker** [comment]
@hispanico @nemesisdesign 
However, Debian 10 still needs to be removed from allowed_failure list!
Should i add a GCI task for that?
